languages = {
  "en": {
    "native": "English",
    "english": "English",
    "appTitle_vote": "Welcome to Voting System",
    "ribbonTitle_vote": "Validate Vote Details",
    "pageTitle_voteDetails": "Enter Vote Details",
    "pageTitle_ballot": "Ballot Paper",
    "instructions_ballot": "Please select a maximum of {{ maxSelections }} choice(s) below. Click on the candidate card to select/deselect.",
    "selectDefaultOption": "Select...",
    "label_societyName": "Society Name:",
    "placeholder_societyName": "SOCIETY NAME",
    "label_communityType": "Choose Community Type:",
    "label_apartmentType": "Apartment",
    "label_individualHomesType": "Individual Homes",
    "label_individualHomesSubType": "Individual Homes Type:",
    "label_homeType_withLanes": "With Lanes",
    "label_homeType_noLanes": "No Lanes",
    "towerLabel": "Tower:",
    "floorLabel": "Floor:",
    "flatLabel": "Flat:",
    "laneLabel": "Lane:",
    "houseNumberLabel": "House Number:",
    "voterHouseIDLabel": "Voter / House ID:",
    "mode_voting": " To vote",
    "mode_check": " Last voted Time",
    "verifyBtn_photo": "Photo",
    "verifyBtn_secretCode": "Secret Code",
    "button_startCam": "Start Cam",
    "button_verifyFace": "Verify Face",
    "button_stopCam": "Stop Cam",
    "button_submitCode": "Submit Code",
    "submitVoteBtn": "Submit Vote",
    "cancelVoteBtn": "Cancel",
    "closeBtn": "Close",
    "cancelVoteTitle": "Confirm Exit",
    "cancelVoteConfirmMessage": "Are you sure you want to cancel your vote? You will be taken back to the start.",
    "yesCancelBtn": "Yes, Cancel",
    "success_jsCheck": "success",
    "thankYou_jsCheck": "thank you",
    "successTitle_thankYou": "Thank You!",
    "successMsg_voteRecorded": "Your vote has been recorded successfully. The application will now close.",
    "message_verificationSuccessLoadingBallot": "Verification Successful. Loading ballot...",
    "proof_voteRecordFound": "Vote Record Found: -------------------- Last Voted On: ",
    "errorTitle_selection": "Selection Error",
    "errorMsg_maxChoicesExceeded": "You can select a maximum of {max_choices} choice(s).",
    "errorTitle_submission": "Submission Error",
    "errorMsg_submittingVote": "Error submitting vote.",
    "errorMsg_network": "A network error occurred. Please try again.",
    "alert_errorFetchingSocietyDetails": "An error occurred while fetching society details.",
    "alert_errorAccessingCamera": "Could not access camera. Please check browser permissions.",
    "alert_selectDetailsFirst": "Please select all details first (Society, Tower, Floor, etc.).",
    "alert_noPhotoCaptured": "No photo captured. Please start the camera first.",
    "alert_noVotingRecordFound": "No voting record found.",
    "alert_alreadyVoted": "You have already voted.",
    "alert_verificationFailed": "Verification failed.",
    "alert_errorPhotoVerification": "An error occurred during photo verification.",
    "alert_selectDetailsAndCode": "Please select all details and enter a secret code.",
    "alert_errorSecretCodeVerification": "An error occurred during secret code verification.",
    "message_fetchingSocietyDetails": "Fetching society details...",
    "message_startingCamera": "Starting camera...",
    "message_verifyingFace": "Verifying face...",
    "message_verifyingCode": "Verifying...",
    "ballotPaper": "Ballot Paper"
  },
  "hi": {
    "native": "हिन्दी",
    "english": "Hindi",
    "appTitle_vote": "मतदान प्रणाली में आपका स्वागत है",
    "ribbonTitle_vote": "वोट विवरण सत्यापित करें",
    "pageTitle_voteDetails": "वोट विवरण दर्ज करें",
    "pageTitle_ballot": "मतपत्र",
    "instructions_ballot": "कृपया नीचे अधिकतम {{ maxSelections }} विकल्प/विकल्पों का चयन करें। चयन/चयन रद्द करने के लिए उम्मीदवार कार्ड पर क्लिक करें।",
    "selectDefaultOption": "चुनें...",
    "label_societyName": "सोसायटी का नाम:",
    "placeholder_societyName": "सोसायटी का नाम",
    "label_communityType": "समुदाय का प्रकार चुनें:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "व्यक्तिगत घर",
    "label_individualHomesSubType": "व्यक्तिगत घरों का प्रकार:",
    "label_homeType_withLanes": "गलियों के साथ",
    "label_homeType_noLanes": "गलियों के बिना",
    "towerLabel": "टॉवर:",
    "floorLabel": "मंजिल:",
    "flatLabel": "फ्लैट:",
    "laneLabel": "गली:",
    "houseNumberLabel": "मकान नंबर:",
    "voterHouseIDLabel": "मतदाता/मकान आईडी:",
    "mode_voting": "वोट करने के लिए",
    "mode_check": "अंतिम मतदान समय",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुप्त कोड",
    "button_startCam": "कैम शुरू करें",
    "button_verifyFace": "चेहरा सत्यापित करें",
    "button_stopCam": "कैम बंद करें",
    "button_submitCode": "कोड सबमिट करें",
    "submitVoteBtn": "वोट सबमिट करें",
    "cancelVoteBtn": "रद्द करें",
    "closeBtn": "बंद करें",
    "cancelVoteTitle": "बाहर निकलने की पुष्टि करें",
    "cancelVoteConfirmMessage": "क्या आप अपना वोट रद्द करना चाहते हैं? आपको वापस शुरुआत में ले जाया जाएगा।",
    "yesCancelBtn": "हाँ, रद्द करें",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "आपका वोट सफलतापूर्वक दर्ज हो गया है। अब एप्लिकेशन बंद हो जाएगा।",
    "message_verificationSuccessLoadingBallot": "सत्यापन सफल। मतपत्र लोड हो रहा है...",
    "proof_voteRecordFound": "वोट रिकॉर्ड मिला: -------------------- अंतिम मतदान:",
    "errorTitle_selection": "चयन त्रुटि",
    "errorMsg_maxChoicesExceeded": "आप अधिकतम {max_choices} विकल्प/विकल्पों का चयन कर सकते हैं।",
    "errorTitle_submission": "सबमिशन त्रुटि",
    "errorMsg_submittingVote": "वोट सबमिट करने में त्रुटि।",
    "errorMsg_network": "एक नेटवर्क त्रुटि हुई। कृपया पुन: प्रयास करें।",
    "alert_errorFetchingSocietyDetails": "सोसायटी का विवरण प्राप्त करते समय एक त्रुटि हुई।",
    "alert_errorAccessingCamera": "कैमरा तक पहुँचा नहीं जा सका। कृपया ब्राउज़र अनुमतियाँ जाँचें।",
    "alert_selectDetailsFirst": "कृपया पहले सभी विवरण चुनें (सोसायटी, टॉवर, मंजिल, आदि)।",
    "alert_noPhotoCaptured": "कोई फोटो कैप्चर नहीं किया गया। कृपया पहले कैमरा शुरू करें।",
    "alert_noVotingRecordFound": "कोई मतदान रिकॉर्ड नहीं मिला।",
    "alert_alreadyVoted": "आप पहले ही वोट दे चुके हैं।",
    "alert_verificationFailed": "सत्यापन विफल रहा।",
    "alert_errorPhotoVerification": "फोटो सत्यापन के दौरान एक त्रुटि हुई।",
    "alert_selectDetailsAndCode": "कृपया सभी विवरण चुनें और एक गुप्त कोड दर्ज करें।",
    "alert_errorSecretCodeVerification": "गुप्त कोड सत्यापन के दौरान एक त्रुटि हुई।",
    "message_fetchingSocietyDetails": "सोसायटी विवरण प्राप्त हो रहा है...",
    "message_startingCamera": "कैमरा शुरू हो रहा है...",
    "message_verifyingFace": "चेहरा सत्यापित हो रहा है...",
    "message_verifyingCode": "सत्यापित हो रहा है...",
    "ballotPaper": "बैलट पेपर"
  },
  "bn": {
    "native": "বাংলা",
    "english": "Bengali",
    "appTitle_vote": "ভোটিং সিস্টেমে স্বাগতম",
    "ribbonTitle_vote": "ভোটের বিবরণ যাচাই করুন",
    "pageTitle_voteDetails": "ভোটের বিবরণ লিখুন",
    "pageTitle_ballot": "ব্যালট পেপার",
    "instructions_ballot": "অনুগ্রহ করে নিচে সর্বোচ্চ {{ maxSelections }} টি পছন্দ নির্বাচন করুন। নির্বাচন/বাতিল করতে প্রার্থীর কার্ডে ক্লিক করুন।",
    "selectDefaultOption": "নির্বাচন করুন...",
    "label_societyName": "সোসাইটির নাম:",
    "placeholder_societyName": "সোসাইটির নাম",
    "label_communityType": "সম্প্রদায়ের প্রকার নির্বাচন করুন:",
    "label_apartmentType": "অ্যাপার্টমেন্ট",
    "label_individualHomesType": "স্বতন্ত্র বাড়ি",
    "label_individualHomesSubType": "স্বতন্ত্র বাড়ির প্রকার:",
    "label_homeType_withLanes": "লেন সহ",
    "label_homeType_noLanes": "লেন ছাড়া",
    "towerLabel": "টাওয়ার:",
    "floorLabel": "ফ্লোর:",
    "flatLabel": "ফ্ল্যাট:",
    "laneLabel": "লেন:",
    "houseNumberLabel": "বাড়ির নম্বর:",
    "voterHouseIDLabel": "ভোটার / বাড়ির আইডি:",
    "mode_voting": "ভোট দিতে",
    "mode_check": "শেষ ভোটের সময়",
    "verifyBtn_photo": "ছবি",
    "verifyBtn_secretCode": "গোপন কোড",
    "button_startCam": "ক্যাম শুরু করুন",
    "button_verifyFace": "মুখ যাচাই করুন",
    "button_stopCam": "ক্যাম বন্ধ করুন",
    "button_submitCode": "কোড জমা দিন",
    "submitVoteBtn": "ভোট জমা দিন",
    "cancelVoteBtn": "বাতিল করুন",
    "closeBtn": "বন্ধ করুন",
    "cancelVoteTitle": "প্রস্থান নিশ্চিত করুন",
    "cancelVoteConfirmMessage": "আপনি কি আপনার ভোট বাতিল করতে নিশ্চিত? আপনাকে শুরুতে ফিরিয়ে নিয়ে যাওয়া হবে।",
    "yesCancelBtn": "হ্যাঁ, বাতিল করুন",
    "success_jsCheck": "সফল",
    "thankYou_jsCheck": "ধন্যবাদ",
    "successTitle_thankYou": "ধন্যবাদ!",
    "successMsg_voteRecorded": "আপনার ভোট সফলভাবে রেকর্ড করা হয়েছে। অ্যাপ্লিকেশনটি এখন বন্ধ হবে।",
    "message_verificationSuccessLoadingBallot": "যাচাই সফল হয়েছে। ব্যালট লোড হচ্ছে...",
    "proof_voteRecordFound": "ভোটের রেকর্ড পাওয়া গেছে: -------------------- শেষ ভোট দেওয়া হয়েছে:",
    "errorTitle_selection": "নির্বাচন ত্রুটি",
    "errorMsg_maxChoicesExceeded": "আপনি সর্বোচ্চ {max_choices} টি পছন্দ নির্বাচন করতে পারেন।",
    "errorTitle_submission": "জমা দেওয়ার ত্রুটি",
    "errorMsg_submittingVote": "ভোট জমা দিতে ত্রুটি।",
    "errorMsg_network": "একটি নেটওয়ার্ক ত্রুটি ঘটেছে। আবার চেষ্টা করুন।",
    "alert_errorFetchingSocietyDetails": "সোসাইটির বিবরণ আনতে গিয়ে একটি ত্রুটি ঘটেছে।",
    "alert_errorAccessingCamera": "ক্যামেরা অ্যাক্সেস করা যায়নি। অনুগ্রহ করে ব্রাউজারের অনুমতিগুলি পরীক্ষা করুন।",
    "alert_selectDetailsFirst": "অনুগ্রহ করে প্রথমে সব বিবরণ নির্বাচন করুন (সোসাইটি, টাওয়ার, ফ্লোর, ইত্যাদি)।",
    "alert_noPhotoCaptured": "কোন ছবি ক্যাপচার করা হয়নি। অনুগ্রহ করে প্রথমে ক্যামেরা শুরু করুন।",
    "alert_noVotingRecordFound": "কোন ভোটের রেকর্ড পাওয়া যায়নি।",
    "alert_alreadyVoted": "আপনি ইতিমধ্যেই ভোট দিয়েছেন।",
    "alert_verificationFailed": "যাচাই ব্যর্থ হয়েছে।",
    "alert_errorPhotoVerification": "ছবি যাচাইয়ের সময় একটি ত্রুটি ঘটেছে।",
    "alert_selectDetailsAndCode": "অনুগ্রহ করে সব বিবরণ নির্বাচন করুন এবং একটি গোপন কোড লিখুন।",
    "alert_errorSecretCodeVerification": "গোপন কোড যাচাইয়ের সময় একটি ত্রুটি ঘটেছে।",
    "message_fetchingSocietyDetails": "সোসাইটির বিবরণ আনা হচ্ছে...",
    "message_startingCamera": "ক্যামেরা শুরু হচ্ছে...",
    "message_verifyingFace": "মুখ যাচাই করা হচ্ছে...",
    "message_verifyingCode": "যাচাই করা হচ্ছে...",
    "ballotPaper": "ব্যালট পেপার"
  },
  "ta": {
    "native": "தமிழ்",
    "english": "Tamil",
    "appTitle_vote": "வாக்குப்பதிவு முறைக்கு வரவேற்கிறோம்",
    "ribbonTitle_vote": "வாக்குச் சரிபார்ப்பு",
    "pageTitle_voteDetails": "விவரம் உள்ளிடுக",
    "pageTitle_ballot": "வாக்குச் சீட்டு",
    "instructions_ballot": "கீழே அதிகபட்சம் {{ maxSelections }} தேர்வுகளைத் தேர்ந்தெடுக்கவும். தேர்ந்தெடுக்க/தேர்வுநீக்க வேட்பாளர் அட்டையைக் கிளிக் செய்யவும்.",
    "selectDefaultOption": "தேர்ந்தெடு...",
    "label_societyName": "சங்கத்தின் பெயர்:",
    "placeholder_societyName": "சங்கத்தின் பெயர்",
    "label_communityType": "சமூக வகையைத் தேர்ந்தெடுக்கவும்:",
    "label_apartmentType": "அபார்ட்மெண்ட்",
    "label_individualHomesType": "தனி வீடுகள்",
    "label_individualHomesSubType": "தனி வீடுகளின் வகை:",
    "label_homeType_withLanes": "பாதைகள் உடன்",
    "label_homeType_noLanes": "பாதைகள் இல்லாமல்",
    "towerLabel": "கோபுரம்:",
    "floorLabel": "தளம்:",
    "flatLabel": "பிளாட்:",
    "laneLabel": "பாதை:",
    "houseNumberLabel": "வீட்டு எண்:",
    "voterHouseIDLabel": "வாக்காளர் / வீட்டு ஐடி:",
    "mode_voting": "வாக்களிக்க",
    "mode_check": "அ. வாக்களித்த நேரம்",
    "verifyBtn_photo": "புகைப்படம்",
    "verifyBtn_secretCode": "ரகசியக் குறியீடு",
    "button_startCam": "கேமராவை தொடங்கு",
    "button_verifyFace": "முகத்தை சரிபார்க்கவும்",
    "button_stopCam": "கேமராவை நிறுத்து",
    "button_submitCode": "குறியீட்டை சமர்ப்பி",
    "submitVoteBtn": "வாக்கைச் சமர்ப்பி",
    "cancelVoteBtn": "ரத்துசெய்",
    "closeBtn": "மூடு",
    "cancelVoteTitle": "வெளியேறுவதை உறுதிப்படுத்து",
    "cancelVoteConfirmMessage": "உங்கள் வாக்கை ரத்து செய்ய நீங்கள் உறுதியாக உள்ளீர்களா? நீங்கள் மீண்டும் தொடக்கத்திற்கு அழைத்துச் செல்லப்படுவீர்கள்.",
    "yesCancelBtn": "ஆம், ரத்துசெய்",
    "success_jsCheck": "வெற்றி",
    "thankYou_jsCheck": "நன்றி",
    "successTitle_thankYou": "நன்றி!",
    "successMsg_voteRecorded": "உங்கள் வாக்கு வெற்றிகரமாகப் பதிவு செய்யப்பட்டுள்ளது. விண்ணப்பம் இப்போது மூடப்படும்.",
    "message_verificationSuccessLoadingBallot": "சரிபார்ப்பு வெற்றி. வாக்குச்சீட்டு ஏற்றப்படுகிறது...",
    "proof_voteRecordFound": "வாக்கு பதிவு கண்டறியப்பட்டது: -------------------- கடைசியாக வாக்களித்தது:",
    "errorTitle_selection": "தேர்வுப் பிழை",
    "errorMsg_maxChoicesExceeded": "நீங்கள் அதிகபட்சம் {max_choices} தேர்வுகளைத் தேர்ந்தெடுக்கலாம்.",
    "errorTitle_submission": "சமர்ப்பிப்புப் பிழை",
    "errorMsg_submittingVote": "வாக்கைச் சமர்ப்பிப்பதில் பிழை.",
    "errorMsg_network": "பிணையப் பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    "alert_errorFetchingSocietyDetails": "சங்கத்தின் விவரங்களைப் பெறும்போது ஒரு பிழை ஏற்பட்டது.",
    "alert_errorAccessingCamera": "கேமராவை அணுக முடியவில்லை. உலாவியின் அனுமதிகளைச் சரிபார்க்கவும்.",
    "alert_selectDetailsFirst": "தயவுசெய்து முதலில் எல்லா விவரங்களையும் தேர்ந்தெடுக்கவும் (சங்கம், கோபுரம், தளம், முதலியன).",
    "alert_noPhotoCaptured": "புகைப்படம் எதுவும் எடுக்கப்படவில்லை. தயவுசெய்து முதலில் கேமராவைத் தொடங்கவும்.",
    "alert_noVotingRecordFound": "வாக்குப்பதிவு பதிவு எதுவும் காணப்படவில்லை.",
    "alert_alreadyVoted": "நீங்கள் ஏற்கனவே வாக்களித்துவிட்டீர்கள்.",
    "alert_verificationFailed": "சரிபார்ப்பு தோல்வியடைந்தது.",
    "alert_errorPhotoVerification": "புகைப்படச் சரிபார்ப்பின் போது ஒரு பிழை ஏற்பட்டது.",
    "alert_selectDetailsAndCode": "தயவுசெய்து அனைத்து விவரங்களையும் தேர்ந்தெடுத்து ரகசியக் குறியீட்டை உள்ளிடவும்.",
    "alert_errorSecretCodeVerification": "ரகசியக் குறியீடு சரிபார்ப்பின் போது ஒரு பிழை ஏற்பட்டது.",
    "message_fetchingSocietyDetails": "சங்கத்தின் விவரங்கள் பெறப்படுகின்றன...",
    "message_startingCamera": "கேமரா தொடங்குகிறது...",
    "message_verifyingFace": "முகம் சரிபார்க்கப்படுகிறது...",
    "message_verifyingCode": "சரிபார்க்கப்படுகிறது...",
    "ballotPaper": "வாக்குப் படிவம்"
  },
  "te": {
    "native": "తెలుగు",
    "english": "Telugu",
    "appTitle_vote": "ఓటింగ్ సిస్టమ్‌కు స్వాగతం",
    "ribbonTitle_vote": "ఓటు వివరాలను ధృవీకరించండి",
    "pageTitle_voteDetails": "ఓటు వివరాలను నమోదు చేయండి",
    "pageTitle_ballot": "బ్యాలెట్ పేపర్",
    "instructions_ballot": "దయచేసి క్రింద గరిష్టంగా {{ maxSelections }} ఎంపిక(ల)ను ఎంచుకోండి. ఎంచుకోవడానికి/ఎంపికను తీసివేయడానికి అభ్యర్థి కార్డుపై క్లిక్ చేయండి.",
    "selectDefaultOption": "ఎంచుకోండి...",
    "label_societyName": "సొసైటీ పేరు:",
    "placeholder_societyName": "సొసైటీ పేరు",
    "label_communityType": "కమ్యూనిటీ రకాన్ని ఎంచుకోండి:",
    "label_apartmentType": "అపార్ట్‌మెంట్",
    "label_individualHomesType": "వ్యక్తిగత గృహాలు",
    "label_individualHomesSubType": "వ్యక్తిగత గృహాల రకం:",
    "label_homeType_withLanes": "లేన్‌లతో",
    "label_homeType_noLanes": "లేన్‌లు లేకుండా",
    "towerLabel": "టవర్:",
    "floorLabel": "ఫ్లోర్:",
    "flatLabel": "ఫ్లాట్:",
    "laneLabel": "లేన్:",
    "houseNumberLabel": "ఇంటి సంఖ్య:",
    "voterHouseIDLabel": "ఓటరు / ఇంటి ID:",
    "mode_voting": "ఓటు వేయడానికి",
    "mode_check": "చివరి ఓటింగ్ సమయం",
    "verifyBtn_photo": "ఫోటో",
    "verifyBtn_secretCode": "రహస్య కోడ్",
    "button_startCam": "కెమెరా ప్రారంభించండి",
    "button_verifyFace": "ముఖాన్ని ధృవీకరించండి",
    "button_stopCam": "కెమెరా ఆపండి",
    "button_submitCode": "కోడ్‌ను సమర్పించండి",
    "submitVoteBtn": "ఓటు సమర్పించండి",
    "cancelVoteBtn": "రద్దు చేయి",
    "closeBtn": "మూసివేయండి",
    "cancelVoteTitle": "నిష్క్రమణను నిర్ధారించండి",
    "cancelVoteConfirmMessage": "మీరు మీ ఓటును రద్దు చేయాలనుకుంటున్నారని మీకు ఖచ్చితంగా ఉందా? మిమ్మల్ని తిరిగి ప్రారంభానికి తీసుకెళ్లబడుతుంది.",
    "yesCancelBtn": "అవును, రద్దు చేయి",
    "success_jsCheck": "విజయం",
    "thankYou_jsCheck": "ధన్యవాదాలు",
    "successTitle_thankYou": "ధన్యవాదాలు!",
    "successMsg_voteRecorded": "మీ ఓటు విజయవంతంగా నమోదు చేయబడింది. అప్లికేషన్ ఇప్పుడు మూసివేయబడుతుంది.",
    "message_verificationSuccessLoadingBallot": "ధృవీకరణ విజయం. బ్యాలెట్ లోడ్ అవుతోంది...",
    "proof_voteRecordFound": "ఓటు రికార్డు కనుగొనబడింది: -------------------- చివరగా ఓటు వేసినది:",
    "errorTitle_selection": "ఎంపిక లోపం",
    "errorMsg_maxChoicesExceeded": "మీరు గరిష్టంగా {max_choices} ఎంపిక(ల)ను ఎంచుకోవచ్చు.",
    "errorTitle_submission": "సమర్పణ లోపం",
    "errorMsg_submittingVote": "ఓటును సమర్పించడంలో లోపం.",
    "errorMsg_network": "నెట్‌వర్క్ లోపం సంభవించింది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    "alert_errorFetchingSocietyDetails": "సొసైటీ వివరాలను పొందుతున్నప్పుడు లోపం సంభవించింది.",
    "alert_errorAccessingCamera": "కెమెరాను యాక్సెస్ చేయలేకపోయాము. దయచేసి బ్రౌజర్ అనుమతులను తనిఖీ చేయండి.",
    "alert_selectDetailsFirst": "దయచేసి ముందుగా అన్ని వివరాలను ఎంచుకోండి (సొసైటీ, టవర్, ఫ్లోర్, మొదలైనవి).",
    "alert_noPhotoCaptured": "ఏ ఫోటో క్యాప్చర్ చేయబడలేదు. దయచేసి ముందుగా కెమెరాను ప్రారంభించండి.",
    "alert_noVotingRecordFound": "ఓటింగ్ రికార్డు ఏదీ కనుగొనబడలేదు.",
    "alert_alreadyVoted": "మీరు ఇప్పటికే ఓటు వేశారు.",
    "alert_verificationFailed": "ధృవీకరణ విఫలమైంది.",
    "alert_errorPhotoVerification": "ఫోటో ధృవీకరణ సమయంలో లోపం సంభవించింది.",
    "alert_selectDetailsAndCode": "దయచేసి అన్ని వివరాలను ఎంచుకుని, రహస్య కోడ్‌ను నమోదు చేయండి.",
    "alert_errorSecretCodeVerification": "రహస్య కోడ్ ధృవీకరణ సమయంలో లోపం సంభవించింది.",
    "message_fetchingSocietyDetails": "సొసైటీ వివరాలు పొందుతోంది...",
    "message_startingCamera": "కెమెరా ప్రారంభమవుతోంది...",
    "message_verifyingFace": "ముఖం ధృవీకరించబడుతోంది...",
    "message_verifyingCode": "ధృవీకరిస్తోంది...",
    "ballotPaper": "బ్యాలెట్ పేపర్"
  },
  "mr": {
    "native": "मराठी",
    "english": "Marathi",
    "appTitle_vote": "मतदान प्रणालीत आपले स्वागत आहे",
    "ribbonTitle_vote": "मतदानाचे तपशील सत्यापित करा",
    "pageTitle_voteDetails": "मतदानाचे तपशील प्रविष्ट करा",
    "pageTitle_ballot": "मतपत्रिका",
    "instructions_ballot": "कृपया खालीलपैकी जास्तीत जास्त {{ maxSelections }} निवड/निवडी करा. निवडण्यासाठी/निवड रद्द करण्यासाठी उमेदवाराच्या कार्डवर क्लिक करा.",
    "selectDefaultOption": "निवडा...",
    "label_societyName": "सोसायटीचे नाव:",
    "placeholder_societyName": "सोसायटीचे नाव",
    "label_communityType": "समुदायाचा प्रकार निवडा:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "स्वतंत्र घरे",
    "label_individualHomesSubType": "स्वतंत्र घरांचा प्रकार:",
    "label_homeType_withLanes": "गल्ल्यांसह",
    "label_homeType_noLanes": "गल्ल्यांशिवाय",
    "towerLabel": "टॉवर:",
    "floorLabel": "मजला:",
    "flatLabel": "फ्लॅट:",
    "laneLabel": "गल्ली:",
    "houseNumberLabel": "घराचा क्रमांक:",
    "voterHouseIDLabel": "मतदार / घर आयडी:",
    "mode_voting": "मतदान करण्यासाठी",
    "mode_check": "शेवटची मतदानाची वेळ",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुप्त कोड",
    "button_startCam": "कॅम सुरू करा",
    "button_verifyFace": "चेहरा सत्यापित करा",
    "button_stopCam": "कॅम बंद करा",
    "button_submitCode": "कोड सबमिट करा",
    "submitVoteBtn": "मत सबमिट करा",
    "cancelVoteBtn": "रद्द करा",
    "closeBtn": "बंद करा",
    "cancelVoteTitle": "बाहेर पडण्याची पुष्टी करा",
    "cancelVoteConfirmMessage": "तुम्ही तुमचे मत रद्द करू इच्छिता याची खात्री आहे का? तुम्हाला पुन्हा सुरुवातीला नेले जाईल.",
    "yesCancelBtn": "होय, रद्द करा",
    "success_jsCheck": "यशस्वी",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "तुमचे मत यशस्वीरित्या नोंदवले गेले आहे. आता ॲप्लिकेशन बंद होईल.",
    "message_verificationSuccessLoadingBallot": "सत्यापन यशस्वी. मतपत्रिका लोड होत आहे...",
    "proof_voteRecordFound": "मत नोंद आढळली: -------------------- शेवटचे मतदान:",
    "errorTitle_selection": "निवड त्रुटी",
    "errorMsg_maxChoicesExceeded": "तुम्ही जास्तीत जास्त {max_choices} निवड/निवडी करू शकता.",
    "errorTitle_submission": "सबमिशन त्रुटी",
    "errorMsg_submittingVote": "मत सबमिट करताना त्रुटी.",
    "errorMsg_network": "नेटवर्कमध्ये त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    "alert_errorFetchingSocietyDetails": "सोसायटीचा तपशील मिळवताना त्रुटी आली.",
    "alert_errorAccessingCamera": "कॅमेरा ॲक्सेस करता आला नाही. कृपया ब्राउझरची अनुमती तपासा.",
    "alert_selectDetailsFirst": "कृपया आधी सर्व तपशील निवडा (सोसायटी, टॉवर, मजला, इ.).",
    "alert_noPhotoCaptured": "कोणताही फोटो कॅप्चर झालेला नाही. कृपया आधी कॅमेरा सुरू करा.",
    "alert_noVotingRecordFound": "कोणतीही मतदानाची नोंद आढळली नाही.",
    "alert_alreadyVoted": "तुम्ही आधीच मतदान केले आहे.",
    "alert_verificationFailed": "सत्यापन अयशस्वी झाले.",
    "alert_errorPhotoVerification": "फोटो पडताळणी दरम्यान एक त्रुटी आली.",
    "alert_selectDetailsAndCode": "कृपया सर्व तपशील निवडा आणि एक गुप्त कोड प्रविष्ट करा.",
    "alert_errorSecretCodeVerification": "गुप्त कोड पडताळणी दरम्यान एक त्रुटी आली.",
    "message_fetchingSocietyDetails": "सोसायटीचा तपशील प्राप्त होत आहे...",
    "message_startingCamera": "कॅमेरा सुरू होत आहे...",
    "message_verifyingFace": "चेहरा सत्यापित होत आहे...",
    "message_verifyingCode": "सत्यापित होत आहे...",
    "ballotPaper": "बॅलट पेपर"
  },
  "kn": {
    "native": "ಕನ್ನಡ",
    "english": "Kannada",
    "appTitle_vote": "ಮತದಾನ ವ್ಯವಸ್ಥೆಗೆ ಸುಸ್ವಾಗತ",
    "ribbonTitle_vote": "ಮತದ ವಿವರಗಳನ್ನು ಮೌಲ್ಯೀಕರಿಸಿ",
    "pageTitle_voteDetails": "ಮತದ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    "pageTitle_ballot": "ಮತಪತ್ರ",
    "instructions_ballot": "ದಯವಿಟ್ಟು ಕೆಳಗೆ ಗರಿಷ್ಠ {{ maxSelections }} ಆಯ್ಕೆ(ಗಳನ್ನು) ಆರಿಸಿ. ಆಯ್ಕೆ ಮಾಡಲು/ಆಯ್ಕೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲು ಅಭ್ಯರ್ಥಿಯ ಕಾರ್ಡ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    "selectDefaultOption": "ಆಯ್ಕೆಮಾಡಿ...",
    "label_societyName": "ಸೊಸೈಟಿ ಹೆಸರು:",
    "placeholder_societyName": "ಸೊಸೈಟಿ ಹೆಸರು",
    "label_communityType": "ಸಮುದಾಯದ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ:",
    "label_apartmentType": "ಅಪಾರ್ಟ್ಮೆಂಟ್",
    "label_individualHomesType": "ವೈಯಕ್ತಿಕ ಮನೆಗಳು",
    "label_individualHomesSubType": "ವೈಯಕ್ತಿಕ ಮನೆಗಳ ಪ್ರಕಾರ:",
    "label_homeType_withLanes": "ಲೇನ್‌ಗಳೊಂದಿಗೆ",
    "label_homeType_noLanes": "ಲೇನ್‌ಗಳಿಲ್ಲದೆ",
    "towerLabel": "ಟವರ್:",
    "floorLabel": "ಮಹಡಿ:",
    "flatLabel": "ಫ್ಲಾಟ್:",
    "laneLabel": "ಲೇನ್:",
    "houseNumberLabel": "ಮನೆ ಸಂಖ್ಯೆ:",
    "voterHouseIDLabel": "ಮತದಾರ / ಮನೆ ಐಡಿ:",
    "mode_voting": "ಮತ ಚಲಾಯಿಸಲು",
    "mode_check": "ಮತದಾನದ ಸಮಯ",
    "verifyBtn_photo": "ಫೋಟೋ",
    "verifyBtn_secretCode": "ರಹಸ್ಯ ಕೋಡ್",
    "button_startCam": "ಕ್ಯಾಮ್ ಪ್ರಾರಂಭಿಸಿ",
    "button_verifyFace": "ಮುಖವನ್ನು ಪರಿಶೀಲಿಸಿ",
    "button_stopCam": "ಕ್ಯಾಮ್ ನಿಲ್ಲಿಸಿ",
    "button_submitCode": "ಕೋಡ್ ಸಲ್ಲಿಸಿ",
    "submitVoteBtn": "ಮತ ಸಲ್ಲಿಸಿ",
    "cancelVoteBtn": "ರದ್ದುಮಾಡು",
    "closeBtn": "ಮುಚ್ಚು",
    "cancelVoteTitle": "ನಿರ್ಗಮನವನ್ನು ದೃಢೀಕರಿಸಿ",
    "cancelVoteConfirmMessage": "ನಿಮ್ಮ ಮತವನ್ನು ರದ್ದುಗೊಳಿಸಲು ನೀವು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುತ್ತೀರಾ? ನಿಮ್ಮನ್ನು ಮತ್ತೆ ಪ್ರಾರಂಭಕ್ಕೆ ಕರೆದೊಯ್ಯಲಾಗುವುದು.",
    "yesCancelBtn": "ಹೌದು, ರದ್ದುಮಾಡು",
    "success_jsCheck": "ಯಶಸ್ಸು",
    "thankYou_jsCheck": "ಧನ್ಯವಾದಗಳು",
    "successTitle_thankYou": "ಧನ್ಯವಾದಗಳು!",
    "successMsg_voteRecorded": "ನಿಮ್ಮ ಮತವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ. ಅಪ್ಲಿಕೇಶನ್ ಈಗ ಮುಚ್ಚಲ್ಪಡುತ್ತದೆ.",
    "message_verificationSuccessLoadingBallot": "ಪರಿಶೀಲನೆ ಯಶಸ್ವಿ. ಮತಪತ್ರವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "proof_voteRecordFound": "ಮತ ದಾಖಲೆ ಕಂಡುಬಂದಿದೆ: -------------------- ಕೊನೆಯ ಮತದಾನ:",
    "errorTitle_selection": "ಆಯ್ಕೆ ದೋಷ",
    "errorMsg_maxChoicesExceeded": "ನೀವು ಗರಿಷ್ಠ {max_choices} ಆಯ್ಕೆ(ಗಳನ್ನು) ಆಯ್ಕೆ ಮಾಡಬಹುದು.",
    "errorTitle_submission": "ಸಲ್ಲಿಸುವಿಕೆ ದೋಷ",
    "errorMsg_submittingVote": "ಮತವನ್ನು ಸಲ್ಲಿಸುವಲ್ಲಿ ದೋಷ.",
    "errorMsg_network": "ನೆಟ್‌ವರ್ಕ್ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "alert_errorFetchingSocietyDetails": "ಸೊಸೈಟಿ ವಿವರಗಳನ್ನು ತರುತ್ತಿರುವಾಗ ದೋಷ ಸಂಭವಿಸಿದೆ.",
    "alert_errorAccessingCamera": "ಕ್ಯಾಮೆರಾವನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಬ್ರೌಸರ್ ಅನುಮತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "alert_selectDetailsFirst": "ದಯವಿಟ್ಟು ಮೊದಲು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ (ಸೊಸೈಟಿ, ಟವರ್, ಮಹಡಿ, ಇತ್ಯಾದಿ).",
    "alert_noPhotoCaptured": "ಯಾವುದೇ ಫೋಟೋವನ್ನು ಸೆರೆಹಿಡಿಯಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ಕ್ಯಾಮೆರಾವನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    "alert_noVotingRecordFound": "ಯಾವುದೇ ಮತದಾನದ ದಾಖಲೆ ಕಂಡುಬಂದಿಲ್ಲ.",
    "alert_alreadyVoted": "ನೀವು ಈಗಾಗಲೇ ಮತ ಹಾಕಿದ್ದೀರಿ.",
    "alert_verificationFailed": "ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ.",
    "alert_errorPhotoVerification": "ಫೋಟೋ ಪರಿಶೀಲನೆಯ ಸಮಯದಲ್ಲಿ ದೋಷ ಸಂಭವಿಸಿದೆ.",
    "alert_selectDetailsAndCode": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ರಹಸ್ಯ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ.",
    "alert_errorSecretCodeVerification": "ರಹಸ್ಯ ಕೋಡ್ ಪರಿಶೀಲನೆಯ ಸಮಯದಲ್ಲಿ ದೋಷ ಸಂಭವಿಸಿದೆ.",
    "message_fetchingSocietyDetails": "ಸೊಸೈಟಿ ವಿವರಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    "message_startingCamera": "ಕ್ಯಾಮೆರಾ ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ...",
    "message_verifyingFace": "ಮುಖವನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "message_verifyingCode": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "ballotPaper": "ಮತಪತ್ರ"
  },
  "gu": {
    "native": "ગુજરાતી",
    "english": "Gujarati",
    "appTitle_vote": "વોટિંગ સિસ્ટમમાં તમારું સ્વાગત છે",
    "ribbonTitle_vote": "વોટ વિગતો માન્ય કરો",
    "pageTitle_voteDetails": "વોટ વિગતો દાખલ કરો",
    "pageTitle_ballot": "મતપત્ર",
    "instructions_ballot": "કૃપા કરીને નીચે વધુમાં વધુ {{ maxSelections }} પસંદગી(ઓ) પસંદ કરો. પસંદ કરવા/પસંદગી રદ કરવા માટે ઉમેદવાર કાર્ડ પર ક્લિક કરો.",
    "selectDefaultOption": "પસંદ કરો...",
    "label_societyName": "સોસાયટીનું નામ:",
    "placeholder_societyName": "સોસાયટીનું નામ",
    "label_communityType": "સમુદાયનો પ્રકાર પસંદ કરો:",
    "label_apartmentType": "એપાર્ટમેન્ટ",
    "label_individualHomesType": "વ્યક્તિગત ઘરો",
    "label_individualHomesSubType": "વ્યક્તિગત ઘરોનો પ્રકાર:",
    "label_homeType_withLanes": "લેન સાથે",
    "label_homeType_noLanes": "લેન વગર",
    "towerLabel": "ટાવર:",
    "floorLabel": "માળ:",
    "flatLabel": "ફ્લેટ:",
    "laneLabel": "લેન:",
    "houseNumberLabel": "ઘર નંબર:",
    "voterHouseIDLabel": "મતદાર / ઘર આઈડી:",
    "mode_voting": "વોટ આપવા માટે",
    "mode_check": "છેલ્લો વોટનો સમય",
    "verifyBtn_photo": "ફોટો",
    "verifyBtn_secretCode": "ગુપ્ત કોડ",
    "button_startCam": "કેમ શરૂ કરો",
    "button_verifyFace": "ચહેરો ચકાસો",
    "button_stopCam": "કેમ બંધ કરો",
    "button_submitCode": "કોડ સબમિટ કરો",
    "submitVoteBtn": "વોટ સબમિટ કરો",
    "cancelVoteBtn": "રદ કરો",
    "closeBtn": "બંધ કરો",
    "cancelVoteTitle": "બહાર નીકળવાની પુષ્ટિ કરો",
    "cancelVoteConfirmMessage": "શું તમે તમારો વોટ રદ કરવા માંગો છો તેની ખાતરી છે? તમને પાછા શરૂઆતમાં લઈ જવામાં આવશે.",
    "yesCancelBtn": "હા, રદ કરો",
    "success_jsCheck": "સફળતા",
    "thankYou_jsCheck": "આભાર",
    "successTitle_thankYou": "આભાર!",
    "successMsg_voteRecorded": "તમારો વોટ સફળતાપૂર્વક નોંધાયો છે. એપ્લિકેશન હવે બંધ થશે.",
    "message_verificationSuccessLoadingBallot": "ચકાસણી સફળ. મતપત્ર લોડ થઈ રહ્યું છે...",
    "proof_voteRecordFound": "વોટ રેકોર્ડ મળ્યો: -------------------- છેલ્લો વોટ આપ્યો:",
    "errorTitle_selection": "પસંદગી ભૂલ",
    "errorMsg_maxChoicesExceeded": "તમે વધુમાં વધુ {max_choices} પસંદગી(ઓ) પસંદ કરી શકો છો.",
    "errorTitle_submission": "સબમિશન ભૂલ",
    "errorMsg_submittingVote": "વોટ સબમિટ કરવામાં ભૂલ.",
    "errorMsg_network": "નેટવર્કમાં ભૂલ આવી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    "alert_errorFetchingSocietyDetails": "સોસાયટીની વિગતો મેળવવામાં ભૂલ આવી.",
    "alert_errorAccessingCamera": "કેમેરા એક્સેસ કરી શકાયો નથી. કૃપા કરીને બ્રાઉઝરની પરવાનગીઓ તપાસો.",
    "alert_selectDetailsFirst": "કૃપા કરીને પહેલા તમામ વિગતો પસંદ કરો (સોસાયટી, ટાવર, માળ, વગેરે).",
    "alert_noPhotoCaptured": "કોઈ ફોટો કેપ્ચર થયો નથી. કૃપા કરીને પહેલા કેમેરા શરૂ કરો.",
    "alert_noVotingRecordFound": "કોઈ વોટિંગ રેકોર્ડ મળ્યો નથી.",
    "alert_alreadyVoted": "તમે પહેલાથી જ વોટ આપી દીધો છે.",
    "alert_verificationFailed": "ચકાસણી નિષ્ફળ રહી.",
    "alert_errorPhotoVerification": "ફોટો ચકાસણી દરમિયાન એક ભૂલ આવી.",
    "alert_selectDetailsAndCode": "કૃપા કરીને તમામ વિગતો પસંદ કરો અને ગુપ્ત કોડ દાખલ કરો.",
    "alert_errorSecretCodeVerification": "ગુપ્ત કોડ ચકાસણી દરમિયાન એક ભૂલ આવી.",
    "message_fetchingSocietyDetails": "સોસાયટીની વિગતો મેળવવામાં આવી રહી છે...",
    "message_startingCamera": "કેમેરા શરૂ થઈ રહ્યો છે...",
    "message_verifyingFace": "ચહેરો ચકાસવામાં આવી રહ્યો છે...",
    "message_verifyingCode": "ચકાસવામાં આવી રહ્યું છે...",
    "ballotPaper": "બેલેટ પેપર",
  },
  "ml": {
    "native": "മലയാളം",
    "english": "Malayalam",
    "appTitle_vote": "വോട്ടിംഗ് സിസ്റ്റത്തിലേക്ക് സ്വാഗതം",
    "ribbonTitle_vote": "വോട്ട് പരിശോധിക്കുക",
    "pageTitle_voteDetails": "വോട്ട് വിവരങ്ങൾ നൽകുക",
    "pageTitle_ballot": "ബാലറ്റ് പേപ്പർ",
    "instructions_ballot": "ദയവായി താഴെ നിന്ന് പരമാവധി {{ maxSelections }} ചോയിസ്(കൾ) തിരഞ്ഞെടുക്കുക. തിരഞ്ഞെടുക്കാൻ/തിരഞ്ഞെടുക്കൽ ഒഴിവാക്കാൻ സ്ഥാനാർത്ഥിയുടെ കാർഡിൽ ക്ലിക്കുചെയ്യുക.",
    "selectDefaultOption": "തിരഞ്ഞെടുക്കുക...",
    "label_societyName": "സോസൈറ്റി പേര്:",
    "placeholder_societyName": "സൊസൈറ്റിയുടെ പേര്",
    "label_communityType": "കമ്മ്യൂണിറ്റി തരം തിരഞ്ഞെടുക്കുക:",
    "label_apartmentType": "അപ്പാർട്ട്മെന്റ്",
    "label_individualHomesType": "വ്യക്തിഗത വീടുകൾ",
    "label_individualHomesSubType": "വ്യക്തിഗത വീടുകളുടെ തരം:",
    "label_homeType_withLanes": "ലൈനുകളോടൊപ്പം",
    "label_homeType_noLanes": "ലൈനുകളില്ലാതെ",
    "towerLabel": "ടവർ:",
    "floorLabel": "ഫ്ലോർ:",
    "flatLabel": "ഫ്ലാറ്റ്:",
    "laneLabel": "ലൈൻ:",
    "houseNumberLabel": "വീട്ട് നമ്പർ:",
    "voterHouseIDLabel": "വോട്ടർ / വീട്ട് ഐഡി:",
    "mode_voting": "വോട്ട് ചെയ്യാൻ",
    "mode_check": "അവസാന വോട്ട്",
    "verifyBtn_photo": "ഫോട്ടോ",
    "verifyBtn_secretCode": "രഹസ്യ കോഡ്",
    "button_startCam": "ക്യാം ആരംഭിക്കുക",
    "button_verifyFace": "മുഖം പരിശോധിക്കുക",
    "button_stopCam": "ക്യാം നിർത്തുക",
    "button_submitCode": "കോഡ് സമർപ്പിക്കുക",
    "submitVoteBtn": "വോട്ട് സമർപ്പിക്കുക",
    "cancelVoteBtn": "റദ്ദാക്കുക",
    "closeBtn": "അടയ്ക്കുക",
    "cancelVoteTitle": "പുറത്തുകടക്കുന്നത് സ്ഥിരീകരിക്കുക",
    "cancelVoteConfirmMessage": "നിങ്ങളുടെ വോട്ട് റദ്ദാക്കാൻ നിങ്ങൾക്ക് ഉറപ്പാണോ? നിങ്ങളെ തിരികെ തുടക്കത്തിലേക്ക് കൊണ്ടുപോകും.",
    "yesCancelBtn": "അതെ, റദ്ദാക്കുക",
    "success_jsCheck": "വിജയം",
    "thankYou_jsCheck": "നന്ദി",
    "successTitle_thankYou": "നന്ദി!",
    "successMsg_voteRecorded": "നിങ്ങളുടെ വോട്ട് വിജയകരമായി രേഖപ്പെടുത്തിയിരിക്കുന്നു. ആപ്ലിക്കേഷൻ ഇപ്പോൾ അടയ്ക്കുന്നതാണ്.",
    "message_verificationSuccessLoadingBallot": "പരിശോധന വിജയം. ബാലറ്റ് ലോഡ് ചെയ്യുന്നു...",
    "proof_voteRecordFound": "വോട്ട് രേഖ കണ്ടെത്തി: -------------------- അവസാനം വോട്ട് ചെയ്തത്:",
    "errorTitle_selection": "തിരഞ്ഞെടുക്കൽ പിശക്",
    "errorMsg_maxChoicesExceeded": "നിങ്ങൾക്ക് പരമാവധി {max_choices} ചോയിസ്(കൾ) തിരഞ്ഞെടുക്കാൻ കഴിയും.",
    "errorTitle_submission": "സമർപ്പിക്കൽ പിശക്",
    "errorMsg_submittingVote": "വോട്ട് സമർപ്പിക്കുമ്പോൾ പിശക്.",
    "errorMsg_network": "ഒരു നെറ്റ്‌വർക്ക് പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "alert_errorFetchingSocietyDetails": "സൊസൈറ്റി വിശദാംശങ്ങൾ എടുക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു.",
    "alert_errorAccessingCamera": "ക്യാമറ ആക്സസ് ചെയ്യാൻ കഴിഞ്ഞില്ല. ദയവായി ബ്രൗസർ അനുമതികൾ പരിശോധിക്കുക.",
    "alert_selectDetailsFirst": "ദയവായി ആദ്യം എല്ലാ വിശദാംശങ്ങളും തിരഞ്ഞെടുക്കുക (സൊസൈറ്റി, ടവർ, ഫ്ലോർ, തുടങ്ങിയവ).",
    "alert_noPhotoCaptured": "ഫോട്ടോയൊന്നും എടുത്തിട്ടില്ല. ദയവായി ആദ്യം ക്യാമറ ആരംഭിക്കുക.",
    "alert_noVotingRecordFound": "വോട്ടിംഗ് രേഖയൊന്നും കണ്ടെത്തിയില്ല.",
    "alert_alreadyVoted": "നിങ്ങൾ ഇതിനകം വോട്ട് ചെയ്തു.",
    "alert_verificationFailed": "പരിശോധന പരാജയപ്പെട്ടു.",
    "alert_errorPhotoVerification": "ഫോട്ടോ പരിശോധനയ്ക്കിടെ ഒരു പിശക് സംഭവിച്ചു.",
    "alert_selectDetailsAndCode": "ദയവായി എല്ലാ വിശദാംശങ്ങളും തിരഞ്ഞെടുത്ത് ഒരു രഹസ്യ കോഡ് നൽകുക.",
    "alert_errorSecretCodeVerification": "രഹസ്യ കോഡ് പരിശോധനയ്ക്കിടെ ഒരു പിശക് സംഭവിച്ചു.",
    "message_fetchingSocietyDetails": "സൊസൈറ്റി വിശദാംശങ്ങൾ എടുക്കുന്നു...",
    "message_startingCamera": "ക്യാമറ ആരംഭിക്കുന്നു...",
    "message_verifyingFace": "മുഖം പരിശോധിക്കുന്നു...",
    "message_verifyingCode": "പരിശോധിക്കുന്നു...",
    "ballotPaper": "ബാലറ്റ് പേപ്പർ"
  },
  "pa": {
    "native": "ਪੰਜਾਬੀ",
    "english": "Punjabi",
    "appTitle_vote": "ਵੋਟਿੰਗ ਸਿਸਟਮ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    "ribbonTitle_vote": "ਵੋਟ ਵੇਰਵਿਆਂ ਦੀ ਜਾਂਚ ਕਰੋ",
    "pageTitle_voteDetails": "ਵੋਟ ਵੇਰਵੇ ਦਰਜ ਕਰੋ",
    "pageTitle_ballot": "ਬੈਲਟ ਪੇਪਰ",
    "instructions_ballot": "ਕਿਰਪਾ ਕਰਕੇ ਹੇਠਾਂ ਵੱਧ ਤੋਂ ਵੱਧ {{ maxSelections }} ਚੋਣਾਂ ਦੀ ਚੋਣ ਕਰੋ। ਚੋਣ ਕਰਨ/ਰੱਦ ਕਰਨ ਲਈ ਉਮੀਦਵਾਰ ਕਾਰਡ 'ਤੇ ਕਲਿੱਕ ਕਰੋ।",
    "selectDefaultOption": "ਚੁਣੋ...",
    "label_societyName": "ਸੋਸਾਇਟੀ ਦਾ ਨਾਮ:",
    "placeholder_societyName": "ਸੋਸਾਇਟੀ ਦਾ ਨਾਮ",
    "label_communityType": "ਕਮਿਊਨਿਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ:",
    "label_apartmentType": "ਅਪਾਰਟਮੈਂਟ",
    "label_individualHomesType": "ਵਿਅਕਤੀਗਤ ਘਰ",
    "label_individualHomesSubType": "ਵਿਅਕਤੀਗਤ ਘਰਾਂ ਦੀ ਕਿਸਮ:",
    "label_homeType_withLanes": "ਲੇਨਾਂ ਸਮੇਤ",
    "label_homeType_noLanes": "ਲੇਨਾਂ ਤੋਂ ਬਿਨਾਂ",
    "towerLabel": "ਟਾਵਰ:",
    "floorLabel": "ਮੰਜ਼ਿਲ:",
    "flatLabel": "ਫਲੈਟ:",
    "laneLabel": "ਲੇਨ:",
    "houseNumberLabel": "ਮਕਾਨ ਨੰਬਰ:",
    "voterHouseIDLabel": "ਵੋਟਰ / ਘਰ ਆਈ.ਡੀ.:",
    "mode_voting": "ਵੋਟ ਪਾਉਣ ਲਈ",
    "mode_check": "ਆਖਰੀ ਵੋਟਿੰਗ ਸਮਾਂ",
    "verifyBtn_photo": "ਫੋਟੋ",
    "verifyBtn_secretCode": "ਗੁਪਤ ਕੋਡ",
    "button_startCam": "ਕੈਮ ਸ਼ੁਰੂ ਕਰੋ",
    "button_verifyFace": "ਚਿਹਰਾ ਤਸਦੀਕ ਕਰੋ",
    "button_stopCam": "ਕੈਮ ਬੰਦ ਕਰੋ",
    "button_submitCode": "ਕੋਡ ਜਮ੍ਹਾ ਕਰੋ",
    "submitVoteBtn": "ਵੋਟ ਜਮ੍ਹਾ ਕਰੋ",
    "cancelVoteBtn": "ਰੱਦ ਕਰੋ",
    "closeBtn": "ਬੰਦ ਕਰੋ",
    "cancelVoteTitle": "ਬਾਹਰ ਜਾਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    "cancelVoteConfirmMessage": "ਕੀ ਤੁਸੀਂ ਆਪਣਾ ਵੋਟ ਰੱਦ ਕਰਨ ਲਈ ਨਿਸ਼ਚਤ ਹੋ? ਤੁਹਾਨੂੰ ਵਾਪਸ ਸ਼ੁਰੂਆਤ ਵਿੱਚ ਲਿਜਾਇਆ ਜਾਵੇਗਾ।",
    "yesCancelBtn": "ਹਾਂ, ਰੱਦ ਕਰੋ",
    "success_jsCheck": "ਸਫਲਤਾ",
    "thankYou_jsCheck": "ਧੰਨਵਾਦ",
    "successTitle_thankYou": "ਧੰਨਵਾਦ!",
    "successMsg_voteRecorded": "ਤੁਹਾਡਾ ਵੋਟ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਕਰ ਲਿਆ ਗਿਆ ਹੈ। ਐਪਲੀਕੇਸ਼ਨ ਹੁਣ ਬੰਦ ਹੋ ਜਾਵੇਗੀ।",
    "message_verificationSuccessLoadingBallot": "ਤਸਦੀਕ ਸਫਲ। ਬੈਲਟ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "proof_voteRecordFound": "ਵੋਟ ਰਿਕਾਰਡ ਮਿਲਿਆ: -------------------- ਆਖਰੀ ਵੋਟ ਪਾਇਆ ਗਿਆ:",
    "errorTitle_selection": "ਚੋਣ ਗਲਤੀ",
    "errorMsg_maxChoicesExceeded": "ਤੁਸੀਂ ਵੱਧ ਤੋਂ ਵੱਧ {max_choices} ਚੋਣਾਂ ਦੀ ਚੋਣ ਕਰ ਸਕਦੇ ਹੋ।",
    "errorTitle_submission": "ਸਬਮਿਸ਼ਨ ਗਲਤੀ",
    "errorMsg_submittingVote": "ਵੋਟ ਜਮ੍ਹਾਂ ਕਰਨ ਵਿੱਚ ਗਲਤੀ।",
    "errorMsg_network": "ਇੱਕ ਨੈੱਟਵਰਕ ਗਲਤੀ ਆਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "alert_errorFetchingSocietyDetails": "ਸੋਸਾਇਟੀ ਦੇ ਵੇਰਵੇ ਪ੍ਰਾਪਤ ਕਰਨ ਵੇਲੇ ਇੱਕ ਗਲਤੀ ਆਈ।",
    "alert_errorAccessingCamera": "ਕੈਮਰੇ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਬ੍ਰਾਊਜ਼ਰ ਦੀਆਂ ਇਜਾਜ਼ਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।",
    "alert_selectDetailsFirst": "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਸਾਰੇ ਵੇਰਵੇ ਚੁਣੋ (ਸੋਸਾਇਟੀ, ਟਾਵਰ, ਮੰਜ਼ਿਲ, ਆਦਿ)।",
    "alert_noPhotoCaptured": "ਕੋਈ ਫੋਟੋ ਕੈਪਚਰ ਨਹੀਂ ਹੋਇਆ। ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਕੈਮਰਾ ਸ਼ੁਰੂ ਕਰੋ।",
    "alert_noVotingRecordFound": "ਕੋਈ ਵੋਟਿੰਗ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
    "alert_alreadyVoted": "ਤੁਸੀਂ ਪਹਿਲਾਂ ਹੀ ਵੋਟ ਪਾ ਚੁੱਕੇ ਹੋ।",
    "alert_verificationFailed": "ਤਸਦੀਕ ਅਸਫਲ ਰਿਹਾ।",
    "alert_errorPhotoVerification": "ਫੋਟੋ ਤਸਦੀਕ ਦੌਰਾਨ ਇੱਕ ਗਲਤੀ ਆਈ।",
    "alert_selectDetailsAndCode": "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਵੇਰਵੇ ਚੁਣੋ ਅਤੇ ਇੱਕ ਗੁਪਤ ਕੋਡ ਦਰਜ ਕਰੋ।",
    "alert_errorSecretCodeVerification": "ਗੁਪਤ ਕੋਡ ਤਸਦੀਕ ਦੌਰਾਨ ਇੱਕ ਗਲਤੀ ਆਈ।",
    "message_fetchingSocietyDetails": "ਸੋਸਾਇਟੀ ਦੇ ਵੇਰਵੇ ਪ੍ਰਾਪਤ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...",
    "message_startingCamera": "ਕੈਮਰਾ ਸ਼ੁਰੂ ਹੋ ਰਿਹਾ ਹੈ...",
    "message_verifyingFace": "ਚਿਹਰਾ ਤਸਦੀਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "message_verifyingCode": "ਤਸਦੀਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
     "ballotPaper": "ਬੈਲਟ ਪੇਪਰ"
  },
  "or": {
    "native": "ଓଡ଼ିଆ",
    "english": "Odia",
    "appTitle_vote": "ଭୋଟିଂ ସିଷ୍ଟମକୁ ସ୍ୱାଗତ",
    "ribbonTitle_vote": "ଭୋଟ୍ ବିବରଣୀ ଯାଞ୍ଚ କରନ୍ତୁ",
    "pageTitle_voteDetails": "ଭୋଟ୍ ବିବରଣୀ ଦାଖଲ କରନ୍ତୁ",
    "pageTitle_ballot": "ବ୍ଯାଲଟ୍ ପେପର",
    "instructions_ballot": "ଦୟାକରି ତଳେ ସର୍ବାଧିକ {{ maxSelections }} ପସନ୍ଦ/ପସନ୍ଦଗୁଡିକ ବାଛନ୍ତୁ। ବାଛିବା/ବାଛିବା ରଦ୍ଦ କରିବା ପାଇଁ ପ୍ରାର୍ଥୀ କାର୍ଡ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ।",
    "selectDefaultOption": "ବାଛନ୍ତୁ...",
    "label_societyName": "ସୋସାଇଟି ନାମ:",
    "placeholder_societyName": "ସୋସାଇଟି ନାମ",
    "label_communityType": "ସମ୍ପ୍ରଦାୟର ପ୍ରକାର ବାଛନ୍ତୁ:",
    "label_apartmentType": "ଆପାର୍ଟମେଣ୍ଟ",
    "label_individualHomesType": "ବ୍ୟକ୍ତିଗତ ଘରଗୁଡ଼ିକ",
    "label_individualHomesSubType": "ବ୍ୟକ୍ତିଗତ ଘରର ପ୍ରକାର:",
    "label_homeType_withLanes": "ଲେନ୍ ସହିତ",
    "label_homeType_noLanes": "ଲେନ୍ ବିନା",
    "towerLabel": "ଟାୱାର:",
    "floorLabel": "ମହଲା:",
    "flatLabel": "ଫ୍ଲାଟ:",
    "laneLabel": "ଲେନ୍:",
    "houseNumberLabel": "ଘର ନମ୍ବର:",
    "voterHouseIDLabel": "ଭୋଟର / ଘର ID:",
    "mode_voting": "ଭୋଟ୍ ଦେବା ପାଇଁ",
    "mode_check": "ଶେଷ ଭୋଟିଂ ସମୟ",
    "verifyBtn_photo": "ଫଟୋ",
    "verifyBtn_secretCode": "ଗୁପ୍ତ କୋଡ୍",
    "button_startCam": "କ୍ୟାମ୍ ଆରମ୍ଭ କରନ୍ତୁ",
    "button_verifyFace": "ମୁହଁ ଯାଞ୍ଚ କରନ୍ତୁ",
    "button_stopCam": "କ୍ୟାମ୍ ବନ୍ଦ କରନ୍ତୁ",
    "button_submitCode": "କୋଡ୍ ଦାଖଲ କରନ୍ତୁ",
    "submitVoteBtn": "ଭୋଟ୍ ଦାଖଲ କରନ୍ତୁ",
    "cancelVoteBtn": "ବାତିଲ କରନ୍ତୁ",
    "closeBtn": "ବନ୍ଦ କରନ୍ତୁ",
    "cancelVoteTitle": "ବାହାରିବା ନିଶ୍ଚିତ କରନ୍ତୁ",
    "cancelVoteConfirmMessage": "ଆପଣ ଆପଣଙ୍କର ଭୋଟ୍ ବାତିଲ କରିବାକୁ ନିଶ୍ଚିତ କି? ଆପଣଙ୍କୁ ପୁନର୍ବାର ଆରମ୍ଭକୁ ନିଆଯିବ।",
    "yesCancelBtn": "ହଁ, ବାତିଲ କରନ୍ତୁ",
    "success_jsCheck": "ସଫଳତା",
    "thankYou_jsCheck": "ଧନ୍ୟବାଦ",
    "successTitle_thankYou": "ଧନ୍ୟବାଦ!",
    "successMsg_voteRecorded": "ଆପଣଙ୍କର ଭୋଟ୍ ସଫଳତାର ସହିତ ରେକର୍ଡ କରାଯାଇଛି। ଆବେଦନ ଏବେ ବନ୍ଦ ହେବ।",
    "message_verificationSuccessLoadingBallot": "ଯାଞ୍ଚ ସଫଳ। ବ୍ୟାଲଟ୍ ଲୋଡ୍ ହେଉଛି...",
    "proof_voteRecordFound": "ଭୋଟ୍ ରେକର୍ଡ ମିଳିଲା: -------------------- ଶେଷ ଭୋଟ୍ ଦିଆଯାଇଥିଲା:",
    "errorTitle_selection": "ଚୟନ ତ୍ରୁଟି",
    "errorMsg_maxChoicesExceeded": "ଆପଣ ସର୍ବାଧିକ {max_choices} ପସନ୍ଦ/ପସନ୍ଦଗୁଡିକ ବାଛିପାରିବେ।",
    "errorTitle_submission": "ଦାଖଲ ତ୍ରୁଟି",
    "errorMsg_submittingVote": "ଭୋଟ୍ ଦାଖଲ କରିବାରେ ତ୍ରୁଟି।",
    "errorMsg_network": "ଏକ ନେଟୱର୍କ ତ୍ରୁଟି ଘଟିଛି। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।",
    "alert_errorFetchingSocietyDetails": "ସୋସାଇଟି ବିବରଣୀ ଫେଚ୍ କରିବା ସମୟରେ ଏକ ତ୍ରୁଟି ଘଟିଛି।",
    "alert_errorAccessingCamera": "କ୍ୟାମେରାକୁ ପ୍ରବେଶ କରାଯାଇପାରିଲା ନାହିଁ। ଦୟାକରି ବ୍ରାଉଜର ଅନୁମତି ଯାଞ୍ଚ କରନ୍ତୁ।",
    "alert_selectDetailsFirst": "ଦୟାକରି ପ୍ରଥମେ ସମସ୍ତ ବିବରଣୀ ବାଛନ୍ତୁ (ସୋସାଇଟି, ଟାୱାର, ମହଲା, ଇତ୍ୟାଦି)।",
    "alert_noPhotoCaptured": "କୌଣସି ଫଟୋ କ୍ୟାପଚର ହୋଇନାହିଁ। ଦୟାକରି ପ୍ରଥମେ କ୍ୟାମେରା ଆରମ୍ଭ କରନ୍ତୁ।",
    "alert_noVotingRecordFound": "କୌଣସି ଭୋଟିଂ ରେକର୍ଡ ମିଳିଲା ନାହିଁ।",
    "alert_alreadyVoted": "ଆପଣ ପୂର୍ବରୁ ହିଁ ଭୋଟ୍ ଦେଇସାରିଛନ୍ତି।",
    "alert_verificationFailed": "ଯାଞ୍ଚ ବିଫଳ ହେଲା।",
    "alert_errorPhotoVerification": "ଫଟୋ ଯାଞ୍ଚ ସମୟରେ ଏକ ତ୍ରୁଟି ଘଟିଛି।",
    "alert_selectDetailsAndCode": "ଦୟାକରି ସମସ୍ତ ବିବରଣୀ ବାଛନ୍ତୁ ଏବଂ ଏକ ଗୁପ୍ତ କୋଡ୍ ଦାଖଲ କରନ୍ତୁ।",
    "alert_errorSecretCodeVerification": "ଗୁପ୍ତ କୋଡ୍ ଯାଞ୍ଚ ସମୟରେ ଏକ ତ୍ରୁଟି ଘଟିଛି।",
    "message_fetchingSocietyDetails": "ସୋସାଇଟି ବିବରଣୀ ଫେଚ୍ ହେଉଛି...",
    "message_startingCamera": "କ୍ୟାମେରା ଆରମ୍ଭ ହେଉଛି...",
    "message_verifyingFace": "ମୁହଁ ଯାଞ୍ଚ ହେଉଛି...",
    "message_verifyingCode": "ଯାଞ୍ଚ ହେଉଛି...",
    "ballotPaper": "ମତ ପତ୍ର",
  },
  "as": {
    "native": "অসমীয়া",
    "english": "Assamese",
    "appTitle_vote": "ভোটিং ব্যৱস্থালৈ স্বাগতম",
    "ribbonTitle_vote": "ভোটৰ বিৱৰণ বৈধ কৰক",
    "pageTitle_voteDetails": "ভোটৰ বিৱৰণ দাখিল কৰক",
    "pageTitle_ballot": "বেলট পেপাৰ",
    "instructions_ballot": "অনুগ্রহ কৰি তলত সৰ্বাধিক {{ maxSelections }} টা পছন্দ বাছনি কৰক। বাছনি কৰিবলৈ/বাছনি উঠাবলৈ প্ৰাৰ্থী কাৰ্ডত ক্লিক কৰক।",
    "selectDefaultOption": "বাছনি কৰক...",
    "label_societyName": "চছাইটিৰ নাম:",
    "placeholder_societyName": "চছাইটিৰ নাম",
    "label_communityType": "সমষ্টিৰ প্ৰকাৰ বাছনি কৰক:",
    "label_apartmentType": "এপাৰ্টমেণ্ট",
    "label_individualHomesType": "ব্যক্তিগত ঘৰ",
    "label_individualHomesSubType": "ব্যক্তিগত ঘৰৰ প্ৰকাৰ:",
    "label_homeType_withLanes": "লেনৰ সৈতে",
    "label_homeType_noLanes": "লেন অবিহনে",
    "towerLabel": "টাৱাৰ:",
    "floorLabel": "মহলা:",
    "flatLabel": "ফ্লেট:",
    "laneLabel": "লেন:",
    "houseNumberLabel": "ঘৰৰ নম্বৰ:",
    "voterHouseIDLabel": "ভোটাৰ / ঘৰৰ ID:",
    "mode_voting": "ভোট দিবলৈ",
    "mode_check": "শেষ ভোট দিয়াৰ সময়",
    "verifyBtn_photo": "ফটো",
    "verifyBtn_secretCode": "গোপন কোড",
    "button_startCam": "কেম আৰম্ভ কৰক",
    "button_verifyFace": "মুখমণ্ডল পৰীক্ষা কৰক",
    "button_stopCam": "কেম বন্ধ কৰক",
    "button_submitCode": "কোড দাখিল কৰক",
    "submitVoteBtn": "ভোট দাখিল কৰক",
    "cancelVoteBtn": "বাতিল কৰক",
    "closeBtn": "বন্ধ কৰক",
    "cancelVoteTitle": "প্ৰস্থান নিশ্চিত কৰক",
    "cancelVoteConfirmMessage": "আপুনি আপোনাৰ ভোট বাতিল কৰিবলৈ নিশ্চিত নে? আপোনাক পুনৰ আৰম্ভণিলৈ লৈ যোৱা হ'ব।",
    "yesCancelBtn": "হয়, বাতিল কৰক",
    "success_jsCheck": "সফলতা",
    "thankYou_jsCheck": "ধন্যবাদ",
    "successTitle_thankYou": "ধন্যবাদ!",
    "successMsg_voteRecorded": "আপোনাৰ ভোট সফলতাৰে ৰেকৰ্ড কৰা হৈছে। এপ্লিকেচন এতিয়া বন্ধ হ'ব।",
    "message_verificationSuccessLoadingBallot": "পৰীক্ষা সফল। বেলট লোড হৈ আছে...",
    "proof_voteRecordFound": "ভোট ৰেকৰ্ড পোৱা গৈছে: -------------------- শেষ ভোটদানৰ তাৰিখ:",
    "errorTitle_selection": "বাছনি ত্ৰুটি",
    "errorMsg_maxChoicesExceeded": "আপুনি সৰ্বাধিক {max_choices} টা পছন্দ বাছনি কৰিব পাৰে।",
    "errorTitle_submission": "দাখিল ত্ৰুটি",
    "errorMsg_submittingVote": "ভোট দাখিল কৰাত ত্ৰুটি।",
    "errorMsg_network": "এটা নেটৱৰ্ক ত্ৰুটি ঘটিছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
    "alert_errorFetchingSocietyDetails": "চছাইটিৰ বিৱৰণ আহৰণ কৰোঁতে এটা ত্ৰুটি ঘটিছে।",
    "alert_errorAccessingCamera": "কেমেৰা ব্যৱহাৰ কৰিব পৰা নগ'ল। অনুগ্ৰহ কৰি ব্ৰাউজাৰৰ অনুমতিসমূহ পৰীক্ষা কৰক।",
    "alert_selectDetailsFirst": "অনুগ্রহ কৰি প্ৰথমে সকলো বিৱৰণ বাছনি কৰক (চছাইটি, টাৱাৰ, মহলা, আদি)।",
    "alert_noPhotoCaptured": "কোনো ফটো কেপচাৰ কৰা হোৱা নাই। অনুগ্ৰহ কৰি প্ৰথমে কেমেৰা আৰম্ভ কৰক।",
    "alert_noVotingRecordFound": "কোনো ভোটিং ৰেকৰ্ড পোৱা নগ'ল।",
    "alert_alreadyVoted": "আপুনি ইতিমধ্যেই ভোট দিছে।",
    "alert_verificationFailed": "পৰীক্ষা বিফল হ'ল।",
    "alert_errorPhotoVerification": "ফটো পৰীক্ষাৰ সময়ত এটা ত্ৰুটি ঘটিছে।",
    "alert_selectDetailsAndCode": "অনুগ্রহ কৰি সকলো বিৱৰণ বাছনি কৰক আৰু এটা গোপন কোড দাখিল কৰক।",
    "alert_errorSecretCodeVerification": "গোপন কোড পৰীক্ষাৰ সময়ত এটা ত্ৰুটি ঘটিছে।",
    "message_fetchingSocietyDetails": "চছাইটিৰ বিৱৰণ আহৰণ কৰা হৈছে...",
    "message_startingCamera": "কেমেৰা আৰম্ভ হৈ আছে...",
    "message_verifyingFace": "মুখমণ্ডল পৰীক্ষা কৰা হৈছে...",
    "message_verifyingCode": "পৰীক্ষা কৰা হৈছে...",
    "ballotPaper": "ভোটৰ কাগজ"
  },
  "ur": {
    "native": "اردو",
    "english": "Urdu",
    "appTitle_vote": "ووٹنگ سسٹم میں خوش آمدید",
    "ribbonTitle_vote": "ووٹ کی تفصیلات کی توثیق کریں",
    "pageTitle_voteDetails": "ووٹ کی تفصیلات درج کریں",
    "pageTitle_ballot": "بیلٹ پیپر",
    "instructions_ballot": "براہ کرم نیچے زیادہ سے زیادہ {{ maxSelections }} انتخاب(ات) منتخب کریں۔ منتخب کرنے/منتخب نہ کرنے کے لیے امیدوار کارڈ پر کلک کریں۔",
    "selectDefaultOption": "منتخب کریں...",
    "label_societyName": "سوسائٹی کا نام:",
    "placeholder_societyName": "سوسائٹی کا نام",
    "label_communityType": "کمیونٹی کی قسم منتخب کریں:",
    "label_apartmentType": "اپارٹمنٹ",
    "label_individualHomesType": "انفرادی گھر",
    "label_individualHomesSubType": "انفرادی گھروں کی قسم:",
    "label_homeType_withLanes": "لینز کے ساتھ",
    "label_homeType_noLanes": "لینز کے بغیر",
    "towerLabel": "ٹاور:",
    "floorLabel": "فلور:",
    "flatLabel": "فلیٹ:",
    "laneLabel": "لین:",
    "houseNumberLabel": "مکان نمبر:",
    "voterHouseIDLabel": "ووٹر / ہاؤس ID:",
    "mode_voting": "ووٹ دینے کے لیے",
    "mode_check": "آخری ووٹنگ کا وقت",
    "verifyBtn_photo": "تصویر",
    "verifyBtn_secretCode": "خفیہ کوڈ",
    "button_startCam": "کیم شروع کریں",
    "button_verifyFace": "چہرے کی تصدیق کریں",
    "button_stopCam": "کیم بند کریں",
    "button_submitCode": "کوڈ جمع کرائیں",
    "submitVoteBtn": "ووٹ جمع کرائیں",
    "cancelVoteBtn": "منسوخ کریں",
    "closeBtn": "بند کریں",
    "cancelVoteTitle": "باہر نکلنے کی تصدیق کریں",
    "cancelVoteConfirmMessage": "کیا آپ اپنا ووٹ منسوخ کرنا چاہتے ہیں؟ آپ کو واپس شروع میں لے جایا جائے گا۔",
    "yesCancelBtn": "ہاں، منسوخ کریں",
    "success_jsCheck": "کامیابی",
    "thankYou_jsCheck": "شکریہ",
    "successTitle_thankYou": "شکریہ!",
    "successMsg_voteRecorded": "آپ کا ووٹ کامیابی سے ریکارڈ ہو گیا ہے۔ ایپلیکیشن اب بند ہو جائے گی۔",
    "message_verificationSuccessLoadingBallot": "تصدیق کامیاب۔ بیلٹ لوڈ ہو رہا ہے...",
    "proof_voteRecordFound": "ووٹ کا ریکارڈ ملا: -------------------- آخری ووٹنگ کا وقت:",
    "errorTitle_selection": "انتخاب کی خرابی",
    "errorMsg_maxChoicesExceeded": "آپ زیادہ سے زیادہ {max_choices} انتخاب(ات) منتخب کر سکتے ہیں۔",
    "errorTitle_submission": "جمع کرانے کی خرابی",
    "errorMsg_submittingVote": "ووٹ جمع کرانے میں خرابی۔",
    "errorMsg_network": "نیٹ ورک میں خرابی پیش آئی۔ براہ کرم دوبارہ کوشش کریں۔",
    "alert_errorFetchingSocietyDetails": "سوسائٹی کی تفصیلات حاصل کرتے وقت ایک خرابی پیش آئی۔",
    "alert_errorAccessingCamera": "کیمرہ تک رسائی حاصل نہیں کی جا سکی۔ براہ کرم براؤزر کی اجازتیں چیک کریں۔",
    "alert_selectDetailsFirst": "براہ کرم پہلے تمام تفصیلات منتخب کریں (سوسائٹی، ٹاور، فلور، وغیرہ)۔",
    "alert_noPhotoCaptured": "کوئی تصویر کیپچر نہیں ہوئی۔ براہ کرم پہلے کیمرا شروع کریں۔",
    "alert_noVotingRecordFound": "کوئی ووٹنگ ریکارڈ نہیں ملا۔",
    "alert_alreadyVoted": "آپ پہلے ہی ووٹ دے چکے ہیں۔",
    "alert_verificationFailed": "تصدیق ناکام ہو گئی۔",
    "alert_errorPhotoVerification": "تصویر کی تصدیق کے دوران ایک خرابی پیش آئی۔",
    "alert_selectDetailsAndCode": "براہ کرم تمام تفصیلات منتخب کریں اور ایک خفیہ کوڈ درج کریں۔",
    "alert_errorSecretCodeVerification": "خفیہ کوڈ کی تصدیق کے دوران ایک خرابی پیش آئی۔",
    "message_fetchingSocietyDetails": "سوسائٹی کی تفصیلات حاصل کی جا رہی ہیں...",
    "message_startingCamera": "کیمرہ شروع ہو رہا ہے...",
    "message_verifyingFace": "چہرے کی تصدیق کی جا رہی ہے...",
    "message_verifyingCode": "تصدیق کی جا رہی ہے...",
    "ballotPaper": "بیلٹ پیپر"
  },
  "ne": {
    "native": "नेपाली",
    "english": "Nepali",
    "appTitle_vote": "मतदान प्रणालीमा स्वागत छ",
    "ribbonTitle_vote": "भोट विवरण प्रमाणित गर्नुहोस्",
    "pageTitle_voteDetails": "भोट विवरण प्रविष्ट गर्नुहोस्",
    "pageTitle_ballot": "मतपत्र",
    "instructions_ballot": "कृपया तल अधिकतम {{ maxSelections }} विकल्प(हरू) चयन गर्नुहोस्। चयन गर्न/रद्द गर्न उम्मेदवार कार्डमा क्लिक गर्नुहोस्।",
    "selectDefaultOption": "चयन गर्नुहोस्...",
    "label_societyName": "सोसाइटीको नाम:",
    "placeholder_societyName": "सोसाइटीको नाम",
    "label_communityType": "सामुदायिक प्रकार छान्नुहोस्:",
    "label_apartmentType": "अपार्टमेन्ट",
    "label_individualHomesType": "व्यक्तिगत घरहरू",
    "label_individualHomesSubType": "व्यक्तिगत घरहरूको प्रकार:",
    "label_homeType_withLanes": "लेनहरूसहित",
    "label_homeType_noLanes": "लेनहरू बिना",
    "towerLabel": "टावर:",
    "floorLabel": "तला:",
    "flatLabel": "फ्ल्याट:",
    "laneLabel": "लेन:",
    "houseNumberLabel": "घर नम्बर:",
    "voterHouseIDLabel": "मतदाता / घर ID:",
    "mode_voting": "भोट गर्नको लागि",
    "mode_check": "अन्तिम मतदान समय",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गोप्य कोड",
    "button_startCam": "क्याम सुरु गर्नुहोस्",
    "button_verifyFace": "अनुहार प्रमाणित गर्नुहोस्",
    "button_stopCam": "क्याम बन्द गर्नुहोस्",
    "button_submitCode": "कोड पेस गर्नुहोस्",
    "submitVoteBtn": "भोट पेस गर्नुहोस्",
    "cancelVoteBtn": "रद्द गर्नुहोस्",
    "closeBtn": "बन्द गर्नुहोस्",
    "cancelVoteTitle": "बाहिरिने पुष्टि गर्नुहोस्",
    "cancelVoteConfirmMessage": "के तपाईं आफ्नो भोट रद्द गर्न निश्चित हुनुहुन्छ? तपाईंलाई सुरुमा फर्काइनेछ।",
    "yesCancelBtn": "हो, रद्द गर्नुहोस्",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "तपाईंको भोट सफलतापूर्वक रेकर्ड गरिएको छ। अनुप्रयोग अब बन्द हुनेछ।",
    "message_verificationSuccessLoadingBallot": "प्रमाणीकरण सफल। मतपत्र लोड हुँदैछ...",
    "proof_voteRecordFound": "भोट रेकर्ड फेला पर्यो: -------------------- अन्तिम मतदान:",
    "errorTitle_selection": "चयन त्रुटि",
    "errorMsg_maxChoicesExceeded": "तपाईं अधिकतम {max_choices} विकल्प(हरू) चयन गर्न सक्नुहुन्छ।",
    "errorTitle_submission": "पेस गर्ने त्रुटि",
    "errorMsg_submittingVote": "भोट पेस गर्नमा त्रुटि।",
    "errorMsg_network": "एक नेटवर्क त्रुटि भयो। कृपया फेरि प्रयास गर्नुहोस्।",
    "alert_errorFetchingSocietyDetails": "सोसाइटीको विवरण ल्याउँदा एक त्रुटि भयो।",
    "alert_errorAccessingCamera": "क्यामेरा पहुँच गर्न सकिएन। कृपया ब्राउजर अनुमतिहरू जाँच गर्नुहोस्।",
    "alert_selectDetailsFirst": "कृपया पहिले सबै विवरणहरू चयन गर्नुहोस् (सोसाइटी, टावर, तला, आदि)।",
    "alert_noPhotoCaptured": "कुनै फोटो क्याप्चर गरिएको छैन। कृपया पहिले क्यामेरा सुरु गर्नुहोस्।",
    "alert_noVotingRecordFound": "कुनै मतदान रेकर्ड फेला परेन।",
    "alert_alreadyVoted": "तपाईंले पहिले नै भोट गरिसक्नुभयो।",
    "alert_verificationFailed": "प्रमाणीकरण असफल भयो।",
    "alert_errorPhotoVerification": "फोटो प्रमाणीकरणको क्रममा एक त्रुटि भयो।",
    "alert_selectDetailsAndCode": "कृपया सबै विवरणहरू चयन गर्नुहोस् र गोप्य कोड प्रविष्ट गर्नुहोस्।",
    "alert_errorSecretCodeVerification": "गोप्य कोड प्रमाणीकरणको क्रममा एक त्रुटि भयो।",
    "message_fetchingSocietyDetails": "सोसाइटीको विवरण ल्याइँदैछ...",
    "message_startingCamera": "क्यामेरा सुरु हुँदैछ...",
    "message_verifyingFace": "अनुहार प्रमाणित गरिँदैछ...",
    "message_verifyingCode": "प्रमाणित गरिँदैछ...",
    "ballotPaper": "मतपत्र"
  },
  "kok": {
    "native": "कोंकणी",
    "english": "Konkani",
    "appTitle_vote": "मतदान पद्धतींत तुमचें स्वागत",
    "ribbonTitle_vote": "मत तपशील मान्यताय",
    "pageTitle_voteDetails": "मत तपशील भरचो",
    "pageTitle_ballot": "मतपत्रिका",
    "instructions_ballot": "कृपया सकुल {{ maxSelections }} निवड/निवड्यो निवडात. निवडपाक/निवड रद्द करपाक उमेदवाराच्या कार्डाचेर क्लिक करात.",
    "selectDefaultOption": "निवडात...",
    "label_societyName": "सोसायटीचें नांव:",
    "placeholder_societyName": "सोसायटीचें नांव",
    "label_communityType": "समुदायाचो प्रकार निवडात:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "वैयक्तिक घरां",
    "label_individualHomesSubType": "वैयक्तिक घरां प्रकार:",
    "label_homeType_withLanes": "लेन आसून",
    "label_homeType_noLanes": "लेन नासून",
    "towerLabel": "टावर:",
    "floorLabel": "मजलो:",
    "flatLabel": "फ्लॅट:",
    "laneLabel": "लेन:",
    "houseNumberLabel": "घराचो नंबर:",
    "voterHouseIDLabel": "मतदार / घर ID:",
    "mode_voting": "मत दिवपाक",
    "mode_check": "निमाणो मतदानाचो वेळ",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुप्त कोड",
    "button_startCam": "कॅम सुरू करा",
    "button_verifyFace": "मुखामळ मान्यताय",
    "button_stopCam": "कॅम बंद करा",
    "button_submitCode": "कोड जमा करा",
    "submitVoteBtn": "मत जमा करा",
    "cancelVoteBtn": "रद्द करा",
    "closeBtn": "बंद करा",
    "cancelVoteTitle": "भायर सरपाची खात्री करा",
    "cancelVoteConfirmMessage": "तुमचें मत रद्द करपाक तुमका खात्री आसा? तुमकां परत सुरवातेक व्हरतले।",
    "yesCancelBtn": "व्हय, रद्द करा",
    "success_jsCheck": "येस",
    "thankYou_jsCheck": "देव बरें करू",
    "successTitle_thankYou": "देव बरें करू!",
    "successMsg_voteRecorded": "तुमचें मत येसस्वीपणान नोंद केल्ले आसा. ॲप्लिकेशन आता बंद जातले।",
    "message_verificationSuccessLoadingBallot": "मान्यताय येसस्वी। मतपत्रिका लोड जाता...",
    "proof_voteRecordFound": "मत नोंद मेळ्ळी: -------------------- निमाणें मत दिल्लें:",
    "errorTitle_selection": "निवड त्रुटी",
    "errorMsg_maxChoicesExceeded": "तुम्ही सकुल {max_choices} निवड/निवड्यो निवडूंक शकता।",
    "errorTitle_submission": "जमा करपाची त्रुटी",
    "errorMsg_submittingVote": "मत जमा करतना त्रुटी।",
    "errorMsg_network": "नेटवर्कांत त्रुटी आयली. कृपया परतून प्रयत्न करात।",
    "alert_errorFetchingSocietyDetails": "सोसायटीचो तपशील मेळयतना एक त्रुटी आयली।",
    "alert_errorAccessingCamera": "कॅमेऱ्याक प्रवेश मेळ्ळो ना. कृपया ब्राउझरची परवानगी तपासची।",
    "alert_selectDetailsFirst": "कृपया पयलीं सगळे तपशील निवडात (सोसायटी, टॉवर, मजलो, आदी)।",
    "alert_noPhotoCaptured": "खंयचोच फोटो कॅप्चर जावंक ना. कृपया पयलीं कॅम सुरू करात।",
    "alert_noVotingRecordFound": "खंयचीच मतदानाची नोंद मेळ्ळी ना।",
    "alert_alreadyVoted": "तुमी पयलींच मत दिल्लें आसा।",
    "alert_verificationFailed": "मान्यताय अपेस जाली।",
    "alert_errorPhotoVerification": "फोटो मान्यतायेच्या वेळार एक त्रुटी आयली।",
    "alert_selectDetailsAndCode": "कृपया सगळे तपशील निवडात आनी एक गुप्त कोड भरचो।",
    "alert_errorSecretCodeVerification": "गुप्त कोड मान्यतायेच्या वेळार एक त्रुटी आयली।",
    "message_fetchingSocietyDetails": "सोसायटीचो तपशील मेळयता...",
    "message_startingCamera": "कॅमेरो सुरू जाता...",
    "message_verifyingFace": "मुखामळ मान्य जाता...",
    "message_verifyingCode": "मान्यताय जाता...",
    "ballotPaper": "मतपत्र"
  },
  "mni": {
    "native": "ꯃꯤꯅꯤꯄꯨꯔꯦꯐꯥ",
    "english": "Manipuri",
    "appTitle_vote": "ꯚꯣꯠ ꯄꯤꯕꯒꯤ ꯁꯤꯁ꯭ꯇꯦꯃꯗ ꯨꯇꯥꯕꯤꯔꯤ",
    "ribbonTitle_vote": "ꯚꯣꯠꯀꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯇꯥꯛꯂꯣ",
    "pageTitle_voteDetails": "ꯚꯣꯠꯀꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯑꯣꯟꯊꯣꯛꯂꯣ",
    "pageTitle_ballot": "ꯕꯦꯂꯣꯠ ꯂꯥꯢꯔꯤꯛ",
    "instructions_ballot": "ꯑꯇꯤꯌꯥ ꯊꯤꯕꯥ {{ maxSelections }} ꯈꯦꯟꯗꯣꯛꯄꯤꯌꯨ. ꯈꯦꯟꯗꯣꯛꯅꯕ/ꯈꯦꯟꯗꯣꯛꯇ꯭ꯔꯤ ꯇꯧꯅꯕ ꯀꯦꯟꯗꯤꯗꯦꯠꯀꯤ ꯀꯥꯔꯗꯇ ꯆꯤꯜꯂꯨ.",
    "selectDefaultOption": "ꯈꯦꯟꯗꯣꯛꯂꯣ...",
    "label_societyName": "ꯁꯣꯁꯥꯢꯇꯤꯒꯤ ꯃꯃꯤꯡ:",
    "placeholder_societyName": "ꯁꯣꯁꯥꯢꯇꯤꯒꯤ ꯃꯃꯤꯡ",
    "label_communityType": "ꯀꯝꯌꯨꯅꯤꯇꯤꯒꯤ ꯃꯈꯜ ꯈꯦꯟꯗꯣꯛꯂꯣ:",
    "label_apartmentType": "ꯑꯄꯥꯔꯠꯃꯦꯟꯇ",
    "label_individualHomesType": "ꯃꯤ ꯑꯃꯃꯒꯤ ꯌꯨꯝ",
    "label_individualHomesSubType": "ꯃꯤ ꯑꯃꯃꯒꯤ ꯌꯨꯝꯒꯤ ꯃꯈꯜ:",
    "label_homeType_withLanes": "ꯂꯦꯟꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ",
    "label_homeType_noLanes": "ꯂꯦꯟꯁꯤꯡ ꯂꯩꯇꯦ",
    "towerLabel": "ꯇꯥꯋꯔ:",
    "floorLabel": "ꯐ꯭ꯂꯣꯔ:",
    "flatLabel": "ꯐ꯭ꯂꯦꯠ:",
    "laneLabel": "ꯂꯦꯟ:",
    "houseNumberLabel": "ꯌꯨꯝꯒꯤ ꯃꯁꯤꯡ:",
    "voterHouseIDLabel": "ꯚꯣꯠ ꯄꯤꯕꯒꯤ/ꯌꯨꯝꯒꯤ ꯑꯥꯢꯗꯤ:",
    "mode_voting": "ꯚꯣꯠ ꯊꯥꯗꯅꯕꯥ꯫",
    "mode_check": "ꯑꯔꯣꯏꯕꯥ ꯚꯣꯠ꯫",
    "verifyBtn_photo": "ꯐꯣꯇꯣ",
    "verifyBtn_secretCode": "ꯑꯔꯣꯜꯕꯥ ꯀꯣꯗ",
    "button_startCam": "ꯀꯦꯃꯦꯔꯥ ꯍꯧꯗꯣꯛꯂꯣ",
    "button_verifyFace": "ꯃꯥꯢ ꯌꯦꯡꯁꯤꯟꯅꯕ",
    "button_stopCam": "ꯀꯦꯃꯦꯔꯥ ꯊꯤꯡꯖꯤꯟꯕ",
    "button_submitCode": "ꯀꯣꯗ ꯊꯥꯗꯣꯛꯂꯣ",
    "submitVoteBtn": "ꯚꯣꯠ ꯊꯥꯗꯣꯛꯂꯣ",
    "cancelVoteBtn": "ꯀꯦꯟꯁꯦꯜ ꯇꯧ",
    "closeBtn": "ꯊꯤꯡꯖꯤꯟꯕ",
    "cancelVoteTitle": "ꯊꯣꯛꯅꯕ ꯑꯌꯦꯛ ꯑꯣꯡꯕ",
    "cancelVoteConfirmMessage": "ꯅꯪꯅ ꯅꯪꯒꯤ ꯚꯣꯠ ꯀꯦꯟꯁꯦꯜ ꯇꯧꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯂꯩꯕ꯭ꯔꯥ? ꯅꯪ ꯍꯧꯗꯣꯛꯐꯝ ꯑꯗꯨꯗ ꯑꯃꯨꯛ ꯍꯟꯅ ꯄꯨꯅꯖꯤꯟꯅꯕꯤꯔꯒꯅꯤ꯫",
    "yesCancelBtn": "ꯍꯥꯏ, ꯀꯦꯟꯁꯦꯜ ꯇꯧ",
    "success_jsCheck": "ꯃꯥꯢꯀꯩ ꯀꯌꯥꯝꯕ",
    "thankYou_jsCheck": "ꯊꯥꯒꯠꯆꯔꯤ",
    "successTitle_thankYou": "ꯊꯥꯒꯠꯆꯔꯤ!",
    "successMsg_voteRecorded": "ꯅꯪꯒꯤ ꯚꯣꯠ ꯑꯁꯤ ꯃꯥꯢꯀꯩ ꯀꯌꯥꯝꯅ ꯔꯦꯀꯣꯔꯗ ꯇꯧꯔꯦ. ꯑꯦꯞꯂꯤꯀꯦꯁꯟ ꯑꯁꯤ ꯍꯥꯟꯅꯥ ꯊꯤꯡꯖꯤꯟꯅꯕꯤꯔꯒꯅꯤ꯫",
    "message_verificationSuccessLoadingBallot": "ꯌꯦꯡꯁꯤꯟꯕ ꯃꯥꯢꯀꯩ ꯀꯌꯥꯝꯕ. ꯕꯦꯂꯣꯠ ꯂꯣꯗ ꯇꯧꯔꯤ...",
    "proof_voteRecordFound": "ꯚꯣꯠ ꯔꯦꯀꯣꯔꯗ ꯐꯪꯂꯦ: -------------------- ꯃꯇꯝ ꯃꯇꯨꯉꯤ ꯚꯣꯠ ꯄꯤꯕꯥ ꯃꯇꯝ:",
    "errorTitle_selection": "ꯈꯦꯟꯗꯣꯛꯄꯒꯤ ꯑꯔꯥꯅꯕ",
    "errorMsg_maxChoicesExceeded": "ꯅꯪꯅ ꯑꯇꯤꯌꯥ ꯊꯤꯕꯥ {max_choices} ꯈꯦꯟꯗꯣꯛꯄꯤꯌꯨ ꯌꯥꯏ.",
    "errorTitle_submission": "ꯊꯥꯗꯣꯛꯄꯒꯤ ꯑꯔꯥꯅꯕ",
    "errorMsg_submittingVote": "ꯚꯣꯠ ꯊꯥꯗꯣꯛꯄꯗ ꯑꯔꯥꯅꯕ ꯊꯣꯛꯂꯦ.",
    "errorMsg_network": "ꯅꯦꯠꯋꯔꯛꯇ ꯑꯔꯥꯅꯕ ꯑꯃ ꯊꯣꯛꯂꯦ. ꯑꯃꯨꯛ ꯍꯟꯅ ꯇꯦꯁ ꯇꯧꯕꯤꯌꯨ.",
    "alert_errorFetchingSocietyDetails": "ꯁꯣꯁꯥꯢꯇꯤꯒꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯐꯪꯅꯕ ꯃꯇꯝꯗ ꯑꯔꯥꯅꯕ ꯑꯃ ꯊꯣꯛꯂꯦ.",
    "alert_errorAccessingCamera": "ꯀꯦꯃꯦꯔꯥ ꯁꯤꯖꯤꯟꯅꯕ ꯌꯥꯗꯦ. ꯕ꯭ꯔꯥꯎꯖꯔꯒꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯌꯦꯡꯁꯤꯟꯕꯤꯌꯨ.",
    "alert_selectDetailsFirst": "ꯃꯇꯝ ꯃꯇꯨꯉꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯈꯦꯟꯗꯣꯛꯂꯣ (ꯁꯣꯁꯥꯢꯇꯤ, ꯇꯥꯋꯔ, ꯐ꯭ꯂꯣꯔ, ꯑꯃꯁꯨꯡ ꯑꯇꯣꯞꯄꯁꯤꯡ).",
    "alert_noPhotoCaptured": "ꯐꯣꯇꯣ ꯀꯔꯤꯃꯠꯇ ꯀꯥꯞꯄꯤꯌꯨꯗꯦ. ꯍꯧꯖꯤꯛꯇꯤ ꯀꯦꯃꯦꯔꯥ ꯍꯧꯗꯣꯛꯂꯣ.",
    "alert_noVotingRecordFound": "ꯚꯣꯠ ꯄꯤꯕꯒꯤ ꯔꯦꯀꯣꯔꯗ ꯀꯔꯤꯃꯠꯇ ꯐꯪꯂꯣꯏ.",
    "alert_alreadyVoted": "ꯅꯪ ꯍꯥꯟꯅꯒꯤ ꯚꯣꯠ ꯄꯤꯈ꯭ꯔꯦ.",
    "alert_verificationFailed": "ꯌꯦꯡꯁꯤꯟꯕ ꯑꯁꯤ ꯑꯔꯥꯅꯕ ꯊꯣꯛꯂꯦ.",
    "alert_errorPhotoVerification": "ꯐꯣꯇꯣ ꯌꯦꯡꯁꯤꯟꯕ ꯃꯇꯝꯗ ꯑꯔꯥꯅꯕ ꯑꯃ ꯊꯣꯛꯂꯦ.",
    "alert_selectDetailsAndCode": "ꯃꯇꯝ ꯃꯇꯨꯉꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯈꯦꯟꯗꯣꯛꯂꯣ ꯑꯃꯁꯨꯡ ꯑꯔꯣꯜꯕꯥ ꯀꯣꯗ ꯑꯃ ꯑꯣꯟꯊꯣꯛꯂꯣ.",
    "alert_errorSecretCodeVerification": "ꯑꯔꯣꯜꯕꯥ ꯀꯣꯗ ꯌꯦꯡꯁꯤꯟꯕ ꯃꯇꯝꯗ ꯑꯔꯥꯅꯕ ꯑꯃ ꯊꯣꯛꯂꯦ.",
    "message_fetchingSocietyDetails": "ꯁꯣꯁꯥꯢꯇꯤꯒꯤ ꯑꯌꯦꯛ ꯑꯣꯡꯕ ꯐꯪꯅꯕ ꯍꯣꯠꯅꯔꯤ...",
    "message_startingCamera": "ꯀꯦꯃꯦꯔꯥ ꯍꯧꯗꯣꯛꯂꯤ...",
    "message_verifyingFace": "ꯃꯥꯢ ꯌꯦꯡꯁꯤꯟꯅꯔꯤ...",
    "message_verifyingCode": "ꯌꯦꯡꯁꯤꯟꯅꯔꯤ...",
    "ballotPaper": "ꯄ꯭ꯂꯥꯠ"
},
  "bho": {
    "native": "भोजपुरी",
    "english": "Bhojpuri",
    "appTitle_vote": "वोटिंग सिस्टम में राउर स्वागत बा",
    "ribbonTitle_vote": "वोट के डिटेल के सत्यापित करीं",
    "pageTitle_voteDetails": "वोट के डिटेल भरें",
    "pageTitle_ballot": "मतपत्र",
    "instructions_ballot": "कृपया नीचे बेसी से बेसी {{ maxSelections }} गो विकल्प चुनीं। चुने खातिर/चुने के रद्द करे खातिर उम्मीदवार कार्ड पर क्लिक करीं।",
    "selectDefaultOption": "चुनीं...",
    "label_societyName": "सोसायटी के नाम:",
    "placeholder_societyName": "सोसायटी के नाम",
    "label_communityType": "कम्युनिटी के प्रकार चुनीं:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "व्यक्तिगत घर",
    "label_individualHomesSubType": "व्यक्तिगत घर के प्रकार:",
    "label_homeType_withLanes": "गली के साथ",
    "label_homeType_noLanes": "गली के बिना",
    "towerLabel": "टावर:",
    "floorLabel": "फ्लोर:",
    "flatLabel": "फ्लैट:",
    "laneLabel": "गली:",
    "houseNumberLabel": "मकान नंबर:",
    "voterHouseIDLabel": "वोटर / हाउस ID:",
    "mode_voting": "वोट करे खातिर",
    "mode_check": "अंतिम वोटिंग समय",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुप्त कोड",
    "button_startCam": "कैम शुरू करीं",
    "button_verifyFace": "चेहरा सत्यापित करीं",
    "button_stopCam": "कैम बंद करीं",
    "button_submitCode": "कोड सबमिट करीं",
    "submitVoteBtn": "वोट सबमिट करीं",
    "cancelVoteBtn": "रद्द करीं",
    "closeBtn": "बंद करीं",
    "cancelVoteTitle": "बाहर निकले के पुष्टि करीं",
    "cancelVoteConfirmMessage": "का रउआ अपना वोट के रद्द करे खातिर निश्चित बानी? रउआ के फेर से शुरू में ले जाइल जाई।",
    "yesCancelBtn": "हाँ, रद्द करीं",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "राउर वोट सफलतापूर्वक रिकॉर्ड कइल गइल बा। एप्लीकेशन अब बंद हो जाई।",
    "message_verificationSuccessLoadingBallot": "सत्यापन सफल। मतपत्र लोड हो रहल बा...",
    "proof_voteRecordFound": "वोट रिकॉर्ड मिलल: -------------------- अंतिम वोटिंग:",
    "errorTitle_selection": "चयन त्रुटि",
    "errorMsg_maxChoicesExceeded": "रउआ बेसी से बेसी {max_choices} गो विकल्प चुनि सकत बानी।",
    "errorTitle_submission": "सबमिशन त्रुटि",
    "errorMsg_submittingVote": "वोट सबमिट करे में त्रुटि।",
    "errorMsg_network": "एक नेटवर्क त्रुटि आइल। कृपया फेर से कोशिश करीं।",
    "alert_errorFetchingSocietyDetails": "सोसायटी के डिटेल लेवे में एक त्रुटि आइल।",
    "alert_errorAccessingCamera": "कैमरा तक पहुँचल ना जा सकल। कृपया ब्राउज़र के अनुमति जाँच करीं।",
    "alert_selectDetailsFirst": "कृपया पहिले सब डिटेल चुनीं (सोसायटी, टावर, फ्लोर, आदि)।",
    "alert_noPhotoCaptured": "कवनो फोटो कैप्चर ना भइल बा। कृपया पहिले कैमरा शुरू करीं।",
    "alert_noVotingRecordFound": "कवनो वोटिंग रिकॉर्ड ना मिलल।",
    "alert_alreadyVoted": "रउआ पहिले ही वोट दे चुकल बानी।",
    "alert_verificationFailed": "सत्यापन विफल रहल।",
    "alert_errorPhotoVerification": "फोटो सत्यापन के दौरान एक त्रुटि आइल।",
    "alert_selectDetailsAndCode": "कृपया सब डिटेल चुनीं आ एक गुप्त कोड दर्ज करीं।",
    "alert_errorSecretCodeVerification": "गुप्त कोड सत्यापन के दौरान एक त्रुटि आइल।",
    "message_fetchingSocietyDetails": "सोसायटी के डिटेल लिहल जा रहल बा...",
    "message_startingCamera": "कैमरा शुरू हो रहल बा...",
    "message_verifyingFace": "चेहरा सत्यापित कइल जा रहल बा...",
    "message_verifyingCode": "सत्यापित कइल जा रहल बा...",
    "ballotPaper": "मतपत्र"
  },
  "kashmiri": {
    "native": "کٲشُر",
    "english": "Kashmiri",
    "appTitle_vote": "ووٗٹِنٛگ نِظامس مَنٛز خٲرَمَقْدَم",
    "ribbonTitle_vote": "ووٗٹَنُک تٔفصٖیل پرٛوِو",
    "pageTitle_voteDetails": "ووٗٹَنُک تٔفصٖیل دٲخل کٔرِو",
    "pageTitle_ballot": "بیلَٹ پؠپَر",
    "instructions_ballot": "مُہربٲنی کٔرِتھ کریو زیٛادٕ کھوتہٕ زیٛادٕ {{ maxSelections }} اِنتِخاب/اِنتِخابَن ہُنٛد چُنوٕ۔ چُنوٕ یا چُنوٕ رَد کَرنہٕ خٲطرٕ اُمیدوار کارڈس پؠٹھ کلِک کٔرِو.",
    "selectDefaultOption": "چُنوٕ...",
    "label_societyName": "سوسایٹی ہُینٛد ناو:",
    "placeholder_societyName": "سوسایٹی ہُینٛد ناو",
    "label_communityType": "کَمٕیوٗنِٹی نِس نَسٕلَس چُنوٕ:",
    "label_apartmentType": "اَپارٹمَنٹ",
    "label_individualHomesType": "اِنفرٲدی گَرٕ",
    "label_individualHomesSubType": "اِنفرٲدی گَرَن ہُینٛد نَسٕل:",
    "label_homeType_withLanes": "لینَن سٲتھ",
    "label_homeType_noLanes": "لینَن بٲغٲر",
    "towerLabel": "ٹاوَر:",
    "floorLabel": "زمیٖن:",
    "flatLabel": "فلیٹ:",
    "laneLabel": "لین:",
    "houseNumberLabel": "گَرٕ نَمبَر:",
    "voterHouseIDLabel": "ووٗٹَر / گَرٕ ID:",
    "mode_voting": "ووٗٹ دِنہٕ خٲطرٕ",
    "mode_check": "ٲخری ووٗٹُنُک وَقٕت",
    "verifyBtn_photo": "فوٗٹو",
    "verifyBtn_secretCode": "خفیہ کوڈ",
    "button_startCam": "کیم شۆروٗع کٔرِو",
    "button_verifyFace": "مُکھٕچ تَصدیٖق کٔرِو",
    "button_stopCam": "کیم بَنٛد کٔرِو",
    "button_submitCode": "کوڈ جَمَع کٔرِو",
    "submitVoteBtn": "ووٗٹ جَمَع کٔرِو",
    "cancelVoteBtn": "رَد کٔرِو",
    "closeBtn": "بَنٛد کٔرِو",
    "cancelVoteTitle": "بٲیِر گَژھنٕچ تَصدیٖق کٔرِو",
    "cancelVoteConfirmMessage": "کیا توٚہی چھوٚ وُوٗٹ رَد کَرنہٕ خٲطرٕ تیَن؟ توٚہؠ گَژھوٚ بؠیہِ شۆروٗعٲتَس نِش۔",
    "yesCancelBtn": "یِہ، رَد کٔرِو",
    "success_jsCheck": "کٲمیٲبی",
    "thankYou_jsCheck": "تھوٚرؠ",
    "successTitle_thankYou": "تھوٚرؠ!",
    "successMsg_voteRecorded": "توٚہؠ سُنٛد ووٗٹ چھُ کٲمیٲبی سٲتھ رِکارڈ کَرنہٕ آمُت۔ اَپلیٖکیشَن گَژھِ اَز بَنٛد۔",
    "message_verificationSuccessLoadingBallot": "تَصدیٖق کٲمیٲبی سٲتھ. بیلَٹ چھُ لوٗڈ گَژھان...",
    "proof_voteRecordFound": "ووٗٹ رِکارڈ لَبنُک: -------------------- ٲخری ووٗٹ دِیُتمُت:",
    "errorTitle_selection": "اِنتِخابس مَنٛز غَلَطی",
    "errorMsg_maxChoicesExceeded": "توٚہی ہیٚکِو زیٛادٕ کھوتہٕ زیٛادٕ {max_choices} اِنتِخاب/اِنتِخابَن ہُنٛد چُنوٕ کٔرِتھ۔",
    "errorTitle_submission": "جَمَع کَرنُک غَلَطی",
    "errorMsg_submittingVote": "ووٗٹ جَمَع کَرنس مَنٛز غَلَطی۔",
    "errorMsg_network": "اَکھ نیٹورٕک غَلَطی گیٔژھ. مُہربٲنی کٔرِتھ بؠیہِ کٔرِو کوشِش.",
    "alert_errorFetchingSocietyDetails": "سوسایٹی ہُینٛد تٔفصٖیل حٲصِل کَرنَس مَنٛز آیہِ اَکھ غَلَطی۔",
    "alert_errorAccessingCamera": "کیمرہ ہؠکوٚ وُصول کَرِتھ نہٕ۔ مُہربٲنی کٔرِتھ براوٗزَرٕچ اِجازَت تہٕ چؠک کٔرِو۔",
    "alert_selectDetailsFirst": "مُہربٲنی کٔرِتھ پَرٛوٹھ کٔرِو سٲری تٔفصٖیل چُنوٕ (سوسایٹی، ٹاوَر، زمیٖن، یِتھ، ٲدِ).",
    "alert_noPhotoCaptured": "کُن فوٗٹو چُنوٕ گٔیۍ نہٕ۔ مُہربٲنی کٔرِتھ پَرٛوٹھ کٔرِو کیم شۆروٗع۔",
    "alert_noVotingRecordFound": "کُن ووٗٹِنٛگ رِکارڈ لَبنُک نہٕ۔",
    "alert_alreadyVoted": "توٚہی چھوٚ پَرٛوٹھٕی ووٗٹ دِیُتمُت۔",
    "alert_verificationFailed": "تَصدیٖق ناکام گیٔۍ۔",
    "alert_errorPhotoVerification": "فوٗٹو تَصدیٖقَس مَنٛز آیہِ اَکھ غَلَطی۔",
    "alert_selectDetailsAndCode": "مُہربٲنی کٔرِتھ سٲری تٔفصٖیل چُنوٕ تہٕ اَکھ خفیہ کوڈ دٲخل کٔرِو۔",
    "alert_errorSecretCodeVerification": "خفیہ کوڈ تَصدیٖقَس مَنٛز آیہِ اَکھ غَلَطی۔",
    "message_fetchingSocietyDetails": "سوسایٹی ہُینٛد تٔفصٖیل چھُ حٲصِل گَژھان...",
    "message_startingCamera": "کیمرہ چھُ شۆروٗع گَژھان...",
    "message_verifyingFace": "مُکھٕچ تَصدیٖق چھِ گَژھان...",
    "message_verifyingCode": "تَصدیٖق چھِ گَژھان...",
    "ballotPaper": "بیلٹ پیپر"
  },
  "mai": {
    "native": "मैथिली",
    "english": "Maithili",
    "appTitle_vote": "मतदान प्रणालीमेँ अहाँक स्वागत अछि",
    "ribbonTitle_vote": "मतदान विवरणक सत्यापन करू",
    "pageTitle_voteDetails": "मतदान विवरण भरू",
    "pageTitle_ballot": "मतपत्र",
    "instructions_ballot": "कृपया नीचाँ अधिक सँ अधिक {{ maxSelections }} विकल्प चुनू। चयन/रद्द करबाक लेल उम्मीदवार कार्ड पर क्लिक करू।",
    "selectDefaultOption": "चुनू...",
    "label_societyName": "सोसाइटीक नाम:",
    "placeholder_societyName": "सोसाइटीक नाम",
    "label_communityType": "समुदायक प्रकार चुनू:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "व्यक्तिगत घर",
    "label_individualHomesSubType": "व्यक्तिगत घरक प्रकार:",
    "label_homeType_withLanes": "गलीक संग",
    "label_homeType_noLanes": "गली बिना",
    "towerLabel": "टावर:",
    "floorLabel": "फ्लोर/मजला:",
    "flatLabel": "फ्लैट:",
    "laneLabel": "गली/लेन:",
    "houseNumberLabel": "मकान नंबर:",
    "voterHouseIDLabel": "मतदाता / घर ID:",
    "mode_voting": "वोट करबाक लेल",
    "mode_check": "अंतिम मतदानक समय",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुप्त कोड",
    "button_startCam": "कैम शुरू करू",
    "button_verifyFace": "मुँहक सत्यापन करू",
    "button_stopCam": "कैम बंद करू",
    "button_submitCode": "कोड जमा करू",
    "submitVoteBtn": "वोट जमा करू",
    "cancelVoteBtn": "रद्द करू",
    "closeBtn": "बंद करू",
    "cancelVoteTitle": "बाहर निकलबाक पुष्टि करू",
    "cancelVoteConfirmMessage": "की अहाँ अपन वोट रद्द करबा लेल निश्चित छी? अहाँकेँ पुनः शुरूमे लऽ जायल जायत।",
    "yesCancelBtn": "हाँ, रद्द करू",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "अहाँक मत सफलतापूर्वक दर्ज कयल गेल अछि। एप्लीकेशन एखन बंद भऽ जायत।",
    "message_verificationSuccessLoadingBallot": "सत्यापन सफल। मतपत्र लोड भऽ रहल अछि...",
    "proof_voteRecordFound": "मतदानक रिकॉर्ड भेटल: -------------------- अंतिम मतदानक तिथि:",
    "errorTitle_selection": "चयन त्रुटि",
    "errorMsg_maxChoicesExceeded": "अहाँ अधिक सँ अधिक {max_choices} विकल्प चुन सकैत छी।",
    "errorTitle_submission": "जमा करबामेँ त्रुटि",
    "errorMsg_submittingVote": "मत जमा करबामेँ त्रुटि।",
    "errorMsg_network": "नेटवर्कमेँ त्रुटि भेल। कृपया पुनः प्रयास करू।",
    "alert_errorFetchingSocietyDetails": "सोसाइटीक विवरण प्राप्त करबामेँ त्रुटि भेल।",
    "alert_errorAccessingCamera": "कैमरा धरि पहुँच नहिं भऽ सकल। कृपया ब्राउजरक अनुमति जाँचू।",
    "alert_selectDetailsFirst": "कृपया पहिने सभ विवरण चुनू (सोसाइटी, टावर, फ्लोर, आदि)।",
    "alert_noPhotoCaptured": "कोनो फोटो कैप्चर नहिं भेल। कृपया पहिने कैमरा शुरू करू।",
    "alert_noVotingRecordFound": "कोनो मतदानक रिकॉर्ड नहिं भेटल।",
    "alert_alreadyVoted": "अहाँ पहिने सँ वोट दऽ चुकल छी।",
    "alert_verificationFailed": "सत्यापन विफल भेल।",
    "alert_errorPhotoVerification": "फोटो सत्यापनक समयमेँ त्रुटि भेल।",
    "alert_selectDetailsAndCode": "कृपया सभ विवरण चुनू आ गुप्त कोड भरू।",
    "alert_errorSecretCodeVerification": "गुप्त कोड सत्यापनक समयमेँ त्रुटि भेल।",
    "message_fetchingSocietyDetails": "सोसाइटीक विवरण प्राप्त भऽ रहल अछि...",
    "message_startingCamera": "कैमरा शुरू भऽ रहल अछि...",
    "message_verifyingFace": "मुँहक सत्यापन भऽ रहल अछि...",
    "message_verifyingCode": "सत्यापन भऽ रहल अछि...",
    "ballotPaper": "मतपत्र"
  },
  "bodo": {
    "native": "बर'/बोडो",
    "english": "Bodo",
    "appTitle_vote": "भट खावनाय बिथिंआव बरायग्रोनाय",
    "ribbonTitle_vote": "भटनि बिसोर खौ बिजाब",
    "pageTitle_voteDetails": "भटनि बिसोर लिरनाय",
    "pageTitle_ballot": "भटनि लाइजाम",
    "instructions_ballot": "अनजाथाव, गाहायनि {{ maxSelections }} सानग्रांबोसेखौ लसै खालाम। सानग्रांबोनि कारदआव थुनानै लसै खालाम/लसै गोजान खालाम।",
    "selectDefaultOption": "लसै खालाम...",
    "label_societyName": "ससायटिनि मुंग:",
    "placeholder_societyName": "ससायटिनि मुंग",
    "label_communityType": "जाथिनि बिथिं खौ लसै खालाम:",
    "label_apartmentType": "एपारतमेन्ट",
    "label_individualHomesType": "सुबुंनि न",
    "label_individualHomesSubType": "सुबुंनि ननि बिथिं:",
    "label_homeType_withLanes": "दावगानायफोरजों",
    "label_homeType_noLanes": "दावगानायफोर गैया",
    "towerLabel": "टवार:",
    "floorLabel": "माहल:",
    "flatLabel": "फ्लाट:",
    "laneLabel": "दावगानाय:",
    "houseNumberLabel": "न नम्बार:",
    "voterHouseIDLabel": "भटार / न ID:",
    "mode_voting": "भट होनायनि",
    "mode_check": "नेवसि भट होनाय सम",
    "verifyBtn_photo": "फथ'",
    "verifyBtn_secretCode": "गुबुन खथ'",
    "button_startCam": "केम जागाय",
    "button_verifyFace": "मोख्रां खौ बिजाब",
    "button_stopCam": "केम खौ बन्द",
    "button_submitCode": "खथ' खौ हरनाय",
    "submitVoteBtn": "भट खौ हरनाय",
    "cancelVoteBtn": "बन्द",
    "closeBtn": "नेवसि",
    "cancelVoteTitle": "ओंखारनाय खौ बिजाब",
    "cancelVoteConfirmMessage": "भट खौ बन्द खालामनाय खौ नों बेजेनाय ना? नों खौ आरोबाव जागायनायआव लांगोन।",
    "yesCancelBtn": "ओँ, बन्द",
    "success_jsCheck": "जागोन",
    "thankYou_jsCheck": "गोजोनथों",
    "successTitle_thankYou": "गोजोनथों!",
    "successMsg_voteRecorded": "भट खौ जागोन थांनायनि लिरनाय जाबाय। एप्लिकेसन खौ नेवसि बन्द जागोन।",
    "message_verificationSuccessLoadingBallot": "जाँच जागोन। भटनि लाइजाम खौ लाबाय थांनाय...",
    "proof_voteRecordFound": "भटनि लिरनाय मोनबाय: -------------------- नेवसि भट खावनाय:",
    "errorTitle_selection": "लसै खालामनायनि बिग्रैनाय",
    "errorMsg_maxChoicesExceeded": "नों {max_choices} सानग्रांबोसेखौ लसै खालामनाय जागोन।",
    "errorTitle_submission": "हरनायनि बिग्रैनाय",
    "errorMsg_submittingVote": "भट खौ हरनायआव बिग्रैनाय।",
    "errorMsg_network": "नेटवारकनि बिग्रैनाय जाबाय। अनजाथाव आरोबाव खामानि खालाम।",
    "alert_errorFetchingSocietyDetails": "ससायटिनि बिसोर खौ लाबाय थांनायआव बिग्रैनाय जाबाय।",
    "alert_errorAccessingCamera": "केमरा खौ लाबाय थांनाय मोनबाय नों। अनजाथाव ब्राउजरनि राहाफोर खौ जाँच।",
    "alert_selectDetailsFirst": "अनजाथाव नेवसि गासै बिसोर खौ लसै खालाम (ससायटि, टवार, माहल, एते)।",
    "alert_noPhotoCaptured": "फथ' खौ लाग्रा मोनबाय नों। अनजाथाव नेवसि केम जागाय।",
    "alert_noVotingRecordFound": "कौनो भट खावनायनि लिरनाय मोनबाय नों।",
    "alert_alreadyVoted": "नों नेवसि भट खावनाय जाबाय।",
    "alert_verificationFailed": "जाँच बिग्रैनाय।",
    "alert_errorPhotoVerification": "फथ' जाँचआव बिग्रैनाय जाबाय।",
    "alert_selectDetailsAndCode": "अनजाथाव गासै बिसोर खौ लसै खालाम आरो गुबुन खथ' खौ लिर।",
    "alert_errorSecretCodeVerification": "गुबुन खथ' जाँचआव बिग्रैनाय जाबाय।",
    "message_fetchingSocietyDetails": "ससायटिनि बिसोर खौ लाबाय थांनाय...",
    "message_startingCamera": "केम जागायनाय...",
    "message_verifyingFace": "मोख्रां खौ बिजाबनाय...",
    "message_verifyingCode": "जाँच खालामनाय...",
    "ballotPaper": "मतपत्र"
  },
  "dogri": {
    "native": "डोगरी",
    "english": "Dogri",
    "appTitle_vote": "वोटिंग सिस्टम च तुसेंगी सुआगत ऐ",
    "ribbonTitle_vote": "वोट दे ब्यौरे दी तस्दीक करो",
    "pageTitle_voteDetails": "वोट दे ब्यौरे दर्ज करो",
    "pageTitle_ballot": "बैलेट पेपर",
    "instructions_ballot": "मेहरबानी करी नीचे जादे शा जादे {{ maxSelections }} चुन्नियां चुन्नो। चुन्नै/चुन्नी रद्द करनै आस्तै उम्मीदवार दे कार्ड पर क्लिक करो।",
    "selectDefaultOption": "चुन्नो...",
    "label_societyName": "सोसाइटी दा नां:",
    "placeholder_societyName": "सोसाइटी दा नां",
    "label_communityType": "कम्युनिटी दी किस्म चुन्नो:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "अक्कले घर",
    "label_individualHomesSubType": "अक्कले घराँ दी किस्म:",
    "label_homeType_withLanes": "लेन कन्नै",
    "label_homeType_noLanes": "लेन बगैर",
    "towerLabel": "टॉवर:",
    "floorLabel": "फ्लोर:",
    "flatLabel": "फ्लैट:",
    "laneLabel": "लेन:",
    "houseNumberLabel": "घर दा नंबर:",
    "voterHouseIDLabel": "वोटर / हाउस आई.डी.:",
    "mode_voting": "वोट करनै आस्तै",
    "mode_check": "पिछले वोट दा बखत",
    "verifyBtn_photo": "फोटो",
    "verifyBtn_secretCode": "गुझ कोड",
    "button_startCam": "कैम शुरू करो",
    "button_verifyFace": "मुंह दी तस्दीक करो",
    "button_stopCam": "कैम बंद करो",
    "button_submitCode": "कोड जमा करो",
    "submitVoteBtn": "वोट जमा करो",
    "cancelVoteBtn": "रद्द करो",
    "closeBtn": "बंद करो",
    "cancelVoteTitle": "बाहर निकलनै दी तस्दीक करो",
    "cancelVoteConfirmMessage": "के तुस अप्पना वोट रद्द करनै आस्तै निश्चित ओ? तुसेंगी शुरू च वापस लै जागन।",
    "yesCancelBtn": "हां, रद्द करो",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवाद",
    "successTitle_thankYou": "धन्यवाद!",
    "successMsg_voteRecorded": "तुसदा वोट सफलता कन्नै दर्ज होई गेआ ऐ। एप्लिेकेशन हुन बंद होई जाग।",
    "message_verificationSuccessLoadingBallot": "तस्दीक सफल। बैलेट लोड होई रेहा ऐ...",
    "proof_voteRecordFound": "वोट रिकॉर्ड मिली गेआ: -------------------- पिछले वोटिंग दी मित्ती:",
    "errorTitle_selection": "चुन्नै दी त्रुटि",
    "errorMsg_maxChoicesExceeded": "तुस जादे शा जादे {max_choices} चुन्नियां चुन्नै सकदे ओ।",
    "errorTitle_submission": "जमा करनै दी त्रुटि",
    "errorMsg_submittingVote": "वोट जमा करनै च त्रुटि।",
    "errorMsg_network": "इक नेटवर्क त्रुटि होई गेई। मेहरबानी करी फ्ही कोशिश करो।",
    "alert_errorFetchingSocietyDetails": "सोसाइटी दे ब्यौरे गी लैंदे बखत इक त्रुटि होई गेई।",
    "alert_errorAccessingCamera": "कैमरे तकर पुज्जी नै सकया। मेहरबानी करी ब्राउज़र दी इजाजतें चेक करो।",
    "alert_selectDetailsFirst": "मेहरबानी करी पंहले सारे ब्यौरे चुन्नो (सोसाइटी, टॉवर, फ्लोर, आदि)।",
    "alert_noPhotoCaptured": "कोई फोटो कैप्चर नै होई। मेहरबानी करी पंहले कैमरा शुरू करो।",
    "alert_noVotingRecordFound": "कोई वोटिंग रिकॉर्ड नै मिली।",
    "alert_alreadyVoted": "तुस पंहले गै वोट करी चुक्के दे ओ।",
    "alert_verificationFailed": "तस्दीक नाकाम होई गेई।",
    "alert_errorPhotoVerification": "फोटो तस्दीक दे दौरान इक त्रुटि होई गेई।",
    "alert_selectDetailsAndCode": "मेहरबानी करी सारे ब्यौरे चुन्नो ते इक गुझ कोड दर्ज करो।",
    "alert_errorSecretCodeVerification": "गुझ कोड तस्दीक दे दौरान इक त्रुटि होई गेई।",
    "message_fetchingSocietyDetails": "सोसाइटी दे ब्यौरे लैंदे जांदे न...",
    "message_startingCamera": "कैमरा शुरू होई रेहा ऐ...",
    "message_verifyingFace": "मुंह दी तस्दीक होई रेही ऐ...",
    "message_verifyingCode": "तस्दीक होई रेही ऐ...",
    "ballotPaper": "मतपत्र"
  },
  "sa": {
    "native": "संस्कृतम्",
    "english": "Sanskrit",
    "appTitle_vote": "मतदान-प्रणाल्यां भवतां स्वागतम्",
    "ribbonTitle_vote": "मतविवरणं मान्यं करोतु",
    "pageTitle_voteDetails": "मतविवरणं प्रविशतु",
    "pageTitle_ballot": "मतपत्रम्",
    "instructions_ballot": "कृपया अधः अधिकतमं {{ maxSelections }} चयनम्/चयन-समूहं वा चिनोतु। चयनार्थं/चयन-त्यागार्थं च अभ्यर्थी-पत्रे (candidate card) क्लिकं करोतु।",
    "selectDefaultOption": "चिनोतु...",
    "label_societyName": "समित्याः नाम:",
    "placeholder_societyName": "समित्याः नाम",
    "label_communityType": "समुदायस्य प्रकारं चिनोतु:",
    "label_apartmentType": "अपार्टमेंट",
    "label_individualHomesType": "व्यक्तिगत-गृहाणि",
    "label_individualHomesSubType": "व्यक्तिगत-गृहाणां प्रकारः:",
    "label_homeType_withLanes": "रथ्याभिः सह",
    "label_homeType_noLanes": "रथ्याभिः विना",
    "towerLabel": "गोपुरम्:",
    "floorLabel": "भूभागः (Floor):",
    "flatLabel": "समतलगृहम् (Flat):",
    "laneLabel": "रथ्या:",
    "houseNumberLabel": "गृह-सङ्ख्या:",
    "voterHouseIDLabel": "मतदाता / गृह-अङ्कः (House ID):",
    "mode_voting": "मतं दातुम्",
    "mode_check": "अन्तिम मतदान-समयः",
    "verifyBtn_photo": "चित्रम्",
    "verifyBtn_secretCode": "गुह्य-सङ्केतः",
    "button_startCam": "चित्रोपकरणं (Cam) आरभ्यताम्",
    "button_verifyFace": "मुखस्य सत्यापनं करोतु",
    "button_stopCam": "चित्रोपकरणं (Cam) स्थग्यताम्",
    "button_submitCode": "सङ्केतं समर्पयतु",
    "submitVoteBtn": "मतं समर्पयतु",
    "cancelVoteBtn": "रद्दं करोतु",
    "closeBtn": "पिधानं करोतु",
    "cancelVoteTitle": "बहिर्गमनं निश्चितं करोतु",
    "cancelVoteConfirmMessage": "किं भवान्/भवती स्वमतं रद्दं कर्तुं निश्चितवान्/वती? भवान्/भवती पुनरारम्भे नीयते।",
    "yesCancelBtn": "आम्, रद्दं करोतु",
    "success_jsCheck": "सफलता",
    "thankYou_jsCheck": "धन्यवादः",
    "successTitle_thankYou": "धन्यवादः!",
    "successMsg_voteRecorded": "भवतः/भवत्याः मतं सफलतापूर्वकं पञ्जीकृतम् अस्ति। अनुप्रयोगः इदानीं पिहितः भविष्यति।",
    "message_verificationSuccessLoadingBallot": "सत्यापनं सफलम्। मतपत्रं भारयते...",
    "proof_voteRecordFound": "मत-पञ्जीकरणं प्राप्तम्: -------------------- अन्तिम-मतदान-तिथि:",
    "errorTitle_selection": "चयन-त्रुटिः",
    "errorMsg_maxChoicesExceeded": "भवान्/भवती अधिकतमं {max_choices} चयनम्/चयन-समूहं वा चिनोतुं शक्नोति।",
    "errorTitle_submission": "समर्पण-त्रुटिः",
    "errorMsg_submittingVote": "मतस्य समर्पणे त्रुटिः।",
    "errorMsg_network": "एकः सञ्जाल-त्रुटिः अभवत्। कृपया पुनः प्रयतताम्।",
    "alert_errorFetchingSocietyDetails": "समित्याः विवरणं प्राप्यमाणे एकः त्रुटिः अभवत्।",
    "alert_errorAccessingCamera": "चित्रोपकरणं (Camera) न प्राप्तम्। कृपया ब्राउज़र-अनुमतीः (browser permissions) परीक्षताम्।",
    "alert_selectDetailsFirst": "कृपया प्रथमं सर्वाणि विवरणानि चिनोतु (समितिः, गोपुरम्, भूभागः, इत्यादयः)।",
    "alert_noPhotoCaptured": "किमपि चित्रं न गृहीतम्। कृपया प्रथमं चित्रोपकरणं (Camera) आरभ्यताम्।",
    "alert_noVotingRecordFound": "किमपि मत-पञ्जीकरणं न प्राप्तम्।",
    "alert_alreadyVoted": "भवान्/भवती पूर्वमेव मतं दत्तवान्/वती।",
    "alert_verificationFailed": "सत्यापनं विफलम् अभवत्।",
    "alert_errorPhotoVerification": "चित्र-सत्यापनस्य समये एकः त्रुटिः अभवत्।",
    "alert_selectDetailsAndCode": "कृपया सर्वाणि विवरणानि चिनोतु तथा च एकं गुह्य-सङ्केतं प्रविशतु।",
    "alert_errorSecretCodeVerification": "गुह्य-सङ्केतस्य सत्यापनस्य समये एकः त्रुटिः अभवत्।",
    "message_fetchingSocietyDetails": "समित्याः विवरणं प्राप्यते...",
    "message_startingCamera": "चित्रोपकरणं (Camera) आरभ्यते...",
    "message_verifyingFace": "मुखस्य सत्यापनं क्रियते...",
    "message_verifyingCode": "सत्यापनं क्रियते...",
    "ballotPaper": "मतपत्रम्"
  },
  "sd": {
    "native": "سنڌي",
    "english": "Sindhi",
    "appTitle_vote": "ووٽنگ سسٽم ۾ ڀليڪار",
    "ribbonTitle_vote": "ووٽ جا تفصيل تصديق ڪريو",
    "pageTitle_voteDetails": "ووٽ جا تفصيل داخل ڪريو",
    "pageTitle_ballot": "بيلٽ پيپر",
    "instructions_ballot": "مهرباني ڪري هيٺ ڏنل وڌ ۾ وڌ {{ maxSelections }} چونڊون چونڊيو. چونڊڻ/نه چونڊڻ لاءِ اميدوار جي ڪارڊ تي ڪلڪ ڪريو.",
    "selectDefaultOption": "چونڊيو...",
    "label_societyName": "سوسائٽي جو نالو:",
    "placeholder_societyName": "سوسائٽي جو نالو",
    "label_communityType": "ڪميونٽي جو قسم چونڊيو:",
    "label_apartmentType": "اپارٽمينٽ",
    "label_individualHomesType": "انفرادي گهر",
    "label_individualHomesSubType": "انفرادي گهر جو قسم:",
    "label_homeType_withLanes": "لينن سان گڏ",
    "label_homeType_noLanes": "لينن کان سواءِ",
    "towerLabel": "ٽاور:",
    "floorLabel": "فلور:",
    "flatLabel": "فليٽ:",
    "laneLabel": "لين:",
    "houseNumberLabel": "گھر جو نمبر:",
    "voterHouseIDLabel": "ووٽر / گهر جي سڃاڻپ (ID):",
    "mode_voting": "ووٽ ڏيڻ لاءِ",
    "mode_check": "آخري ووٽ ڏيڻ جو وقت",
    "verifyBtn_photo": "فوٽو",
    "verifyBtn_secretCode": "ڳجهو ڪوڊ",
    "button_startCam": "ڪئميرا شروع ڪريو",
    "button_verifyFace": "منهن جي تصديق ڪريو",
    "button_stopCam": "ڪئميرا بند ڪريو",
    "button_submitCode": "ڪوڊ جمع ڪرايو",
    "submitVoteBtn": "ووٽ جمع ڪرايو",
    "cancelVoteBtn": "رد ڪريو",
    "closeBtn": "بند ڪريو",
    "cancelVoteTitle": "نڪرڻ جي تصديق ڪريو",
    "cancelVoteConfirmMessage": "ڇا توهان پڪ آهيو ته توهان پنهنجو ووٽ رد ڪرڻ چاهيو ٿا؟ توهان کي شروعات ڏانهن واپس ورتو ويندو.",
    "yesCancelBtn": "ها، رد ڪريو",
    "success_jsCheck": "ڪاميابي",
    "thankYou_jsCheck": "مهرباني",
    "successTitle_thankYou": "مهرباني!",
    "successMsg_voteRecorded": "توهان جو ووٽ ڪاميابي سان رڪارڊ ڪيو ويو آهي. ايپليڪيشن هاڻي بند ٿي ويندي.",
    "message_verificationSuccessLoadingBallot": "تصديق ڪامياب ٿي. بيلٽ لوڊ ٿي رهيو آهي...",
    "proof_voteRecordFound": "ووٽ جو رڪارڊ مليو: -------------------- آخري ووٽ ڏنل:",
    "errorTitle_selection": "چونڊ جي غلطي",
    "errorMsg_maxChoicesExceeded": "توهان وڌ ۾ وڌ {max_choices} چونڊون ڪري سگهو ٿا.",
    "errorTitle_submission": "جمع ڪرائڻ جي غلطي",
    "errorMsg_submittingVote": "ووٽ جمع ڪرائڻ ۾ غلطي ٿي وئي.",
    "errorMsg_network": "هڪ نيٽورڪ غلطي ٿي وئي. مهرباني ڪري ٻيهر ڪوشش ڪريو.",
    "alert_errorFetchingSocietyDetails": "سوسائٽي جا تفصيل حاصل ڪرڻ دوران هڪ غلطي ٿي وئي.",
    "alert_errorAccessingCamera": "ڪئميرا تائين رسائي نه ٿي سگهي. مهرباني ڪري برائوزر جي اجازت چيڪ ڪريو.",
    "alert_selectDetailsFirst": "مهرباني ڪري پهرين سڀ تفصيل چونڊيو (سوسائٽي، ٽاور، فلور، وغيره).",
    "alert_noPhotoCaptured": "ڪو به فوٽو ڪڍيو نه ويو آهي. مهرباني ڪري پهرين ڪئميرا شروع ڪريو.",
    "alert_noVotingRecordFound": "ڪو به ووٽنگ رڪارڊ نه مليو.",
    "alert_alreadyVoted": "توهان اڳ ۾ ئي ووٽ ڏئي چڪا آهيو.",
    "alert_verificationFailed": "تصديق ناڪام ٿي.",
    "alert_errorPhotoVerification": "فوٽو جي تصديق دوران هڪ غلطي ٿي وئي.",
    "alert_selectDetailsAndCode": "مهرباني ڪري سڀ تفصيل چونڊيو ۽ هڪ ڳجهو ڪوڊ داخل ڪريو.",
    "alert_errorSecretCodeVerification": "ڳجهي ڪوڊ جي تصديق دوران هڪ غلطي ٿي وئي.",
    "message_fetchingSocietyDetails": "سوسائٽي جا تفصيل حاصل ڪيا پيا وڃن...",
    "message_startingCamera": "ڪئميرا شروع ڪيو پيو وڃي...",
    "message_verifyingFace": "منهن جي تصديق ڪئي پئي وڃي...",
    "message_verifyingCode": "تصديق ڪئي پئي وڃي...",
    "ballotPaper": "ووٽ پرچي"
  },
  "sat": {
    "native": "ᱥᱟᱱᱛᱟᱲᱤ",
    "english": "Santali",
    "appTitle_vote": "ᱵᱷᱳᱴᱤᱝ ᱵᱮᱵᱷᱟᱨ ᱜᱷᱟᱨ ᱨᱮ ᱟᱫᱚᱨ",
    "ribbonTitle_vote": "ᱵᱷᱳᱴ ᱵᱤᱵᱚᱨᱚᱱ ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
    "pageTitle_voteDetails": "ᱵᱷᱳᱴ ᱵᱤᱵᱚᱨᱚᱱ ᱵᱷᱚᱨᱟᱣ ᱢᱮ",
    "pageTitle_ballot": "ᱵᱷᱳᱴ ᱥᱟᱦᱮᱫ",
    "instructions_ballot": "ᱫᱚᱭᱟ ᱠᱟᱛᱮ {{ maxSelections }} ᱵᱟᱪᱷᱟᱣ ᱠᱷᱚᱱ ᱡᱟᱹᱥᱛᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾ ᱵᱟᱪᱷᱟᱣ/ᱵᱟᱪᱷᱟᱣ ᱵᱟᱹᱜᱤ ᱞᱟᱹᱜᱤᱫ ᱠᱮᱱᱰᱤᱰᱮᱴ ᱠᱟᱨᱰ ᱨᱮ ᱪᱷᱩᱢ ᱢᱮ᱾",
    "selectDefaultOption": "ᱵᱟᱪᱷᱟᱣ ᱢᱮ...",
    "label_societyName": "ᱥᱚᱥᱟᱭᱴᱤ ᱧᱩᱛᱩᱢ:",
    "placeholder_societyName": "ᱥᱚᱥᱟᱭᱴᱤ ᱧᱩᱛᱩᱢ",
    "label_communityType": "ᱡᱟᱹᱛ ᱯᱚᱨᱠᱟᱨ ᱵᱟᱪᱷᱟᱣ ᱢᱮ:",
    "label_apartmentType": "ᱟᱯᱟᱨᱴᱢᱮᱱᱴ",
    "label_individualHomesType": "ᱢᱤᱫ ᱢᱤᱫ ᱚᱲᱟᱜ",
    "label_individualHomesSubType": "ᱢᱤᱫ ᱢᱤᱫ ᱚᱲᱟᱜ ᱯᱚᱨᱠᱟᱨ:",
    "label_homeType_withLanes": "ᱞᱮᱱ ᱥᱟᱶᱛᱮ",
    "label_homeType_noLanes": "ᱞᱮᱱ ᱵᱟᱹᱜᱤ",
    "towerLabel": "ᱴᱟᱣᱚᱨ:",
    "floorLabel": "ᱯᱷᱚᱞᱚᱨ:",
    "flatLabel": "ᱯᱷᱮᱞᱴ:",
    "laneLabel": "ᱞᱮᱱ:",
    "houseNumberLabel": "ᱚᱲᱟᱜ ᱱᱚᱢᱵᱚᱨ:",
    "voterHouseIDLabel": "ᱵᱷᱳᱴᱟᱨ / ᱚᱲᱟᱜ ID:",
    "mode_voting": "ᱵᱷᱳᱴ ᱮᱢᱟ ᱞᱟᱹᱜᱤᱫ",
    "mode_check": "ᱢᱩᱪᱟᱹᱫ ᱵᱷᱳᱴ ᱚᱠᱛᱚ",
    "verifyBtn_photo": "ᱯᱷᱚᱴᱚ",
    "verifyBtn_secretCode": "ᱞᱩᱠᱩ ᱠᱚᱰ",
    "button_startCam": "ᱠᱮᱢ ᱮᱛᱚᱦᱚᱵ ᱢᱮ",
    "button_verifyFace": "ᱢᱚᱪᱟ ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
    "button_stopCam": "ᱠᱮᱢ ᱵᱚᱱᱫᱽ ᱢᱮ",
    "button_submitCode": "ᱠᱚᱰ ᱮᱢ ᱢᱮ",
    "submitVoteBtn": "ᱵᱷᱳᱴ ᱮᱢ ᱢᱮ",
    "cancelVoteBtn": "ᱵᱟᱹᱛᱤᱞ ᱢᱮ",
    "closeBtn": "ᱵᱚᱱᱫᱽ ᱢᱮ",
    "cancelVoteTitle": "ᱵᱟᱹᱜᱤᱭᱟᱹᱣ ᱨᱮ ᱥᱚᱛᱷᱤᱠ ᱢᱮ",
    "cancelVoteConfirmMessage": "ᱟᱢ ᱵᱷᱳᱴ ᱵᱟᱹᱛᱤᱞ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱛᱷᱤᱠ ᱜᱮᱭᱟᱢ? ᱟᱢ ᱫᱚ ᱚᱛᱚᱦᱚᱵ ᱨᱮ ᱯᱷᱮᱨᱟᱣ ᱢᱮᱭᱟ.",
    "yesCancelBtn": "ᱦᱚᱭ, ᱵᱟᱹᱛᱤᱞ ᱢᱮ",
    "success_jsCheck": "ᱥᱚᱯᱷᱚᱞᱚ",
    "thankYou_jsCheck": "ᱥᱟᱨᱦᱟᱣ",
    "successTitle_thankYou": "ᱥᱟᱨᱦᱟᱣ!",
    "successMsg_voteRecorded": "ᱟᱢᱟᱜ ᱵᱷᱳᱴ ᱥᱚᱯᱷᱚᱞᱚ ᱛᱮ ᱨᱮᱠᱚᱨᱰ ᱟᱠᱟᱱᱟ᱾ ᱮᱯᱞᱤᱠᱮᱥᱚᱱ ᱫᱚ ᱱᱤᱛᱚᱜ ᱵᱚᱱᱫᱽᱚᱜᱼᱟ᱾",
    "message_verificationSuccessLoadingBallot": "ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱥᱚᱯᱷᱚᱞᱚ᱾ ᱵᱷᱳᱴ ᱥᱟᱦᱮᱫ ᱞᱚᱰᱚᱜ ᱠᱟᱱᱟ...",
    "proof_voteRecordFound": "ᱵᱷᱳᱴ ᱨᱮᱠᱚᱨᱰ ᱧᱟᱢ ᱟᱠᱟᱱᱟ: -------------------- ᱢᱩᱪᱟᱹᱫ ᱵᱷᱳᱴ ᱮᱢ ᱟᱠᱟᱱ ᱛᱟᱦᱮᱸᱫ:",
    "errorTitle_selection": "ᱵᱟᱪᱷᱟᱣ ᱮᱨᱚᱨ",
    "errorMsg_maxChoicesExceeded": "ᱟᱢ ᱡᱟᱹᱥᱛᱤ ᱛᱮ {max_choices} ᱵᱟᱪᱷᱟᱣ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ᱾",
    "errorTitle_submission": "ᱮᱢ ᱮᱨᱚᱨ",
    "errorMsg_submittingVote": "ᱵᱷᱳᱴ ᱮᱢ ᱮᱨᱚᱨ᱾",
    "errorMsg_network": "ᱢᱤᱫᱴᱮᱡᱽ ᱱᱮᱴᱣᱚᱨᱠ ᱮᱨᱚᱨ ᱦᱩᱭ ᱟᱠᱟᱱᱟ᱾ ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱟᱨᱦᱚᱸ ᱪᱮᱥᱴᱟ ᱢᱮ᱾",
    "alert_errorFetchingSocietyDetails": "ᱥᱚᱥᱟᱭᱴᱤ ᱵᱤᱵᱚᱨᱚᱱ ᱞᱟᱹᱜᱤᱫ ᱮᱨᱚᱨ ᱦᱩᱭ ᱟᱠᱟᱱᱟ᱾",
    "alert_errorAccessingCamera": "ᱠᱮᱢᱮᱨᱟ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ᱾ ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱵᱨᱟᱣᱡᱟᱨ ᱨᱮᱱᱟᱜ ᱮᱢ ᱟᱠᱟᱱ ᱧᱮᱞ ᱢᱮ᱾",
    "alert_selectDetailsFirst": "ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱡᱚᱛᱚ ᱵᱤᱵᱚᱨᱚᱱ ᱯᱩᱭᱞᱩ ᱵᱟᱪᱷᱟᱣ ᱢᱮ (ᱥᱚᱥᱟᱭᱴᱤ, ᱴᱟᱣᱚᱨ, ᱯᱷᱚᱞᱚᱨ, ᱚᱱᱠᱟ ᱠᱚ)᱾",
    "alert_noPhotoCaptured": "ᱯᱷᱚᱴᱚ ᱵᱟᱝ ᱠᱮᱯᱪᱟᱨ ᱟᱠᱟᱱᱟ᱾ ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱯᱩᱭᱞᱩ ᱠᱮᱢᱮᱨᱟ ᱮᱛᱚᱦᱚᱵ ᱢᱮ᱾",
    "alert_noVotingRecordFound": "ᱠᱚᱱᱚ ᱵᱷᱳᱴ ᱨᱮᱠᱚᱨᱰ ᱵᱟᱝ ᱧᱟᱢ ᱟᱠᱟᱱᱟ᱾",
    "alert_alreadyVoted": "ᱟᱢ ᱢᱟᱲᱟᱝ ᱠᱷᱚᱱ ᱵᱷᱳᱴ ᱮᱢ ᱟᱠᱟᱫᱟ᱾",
    "alert_verificationFailed": "ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱯᱷᱮᱞ ᱮᱱᱟ᱾",
    "alert_errorPhotoVerification": "ᱯᱷᱚᱴᱚ ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱨᱮ ᱮᱨᱚᱨ ᱦᱩᱭ ᱟᱠᱟᱱᱟ᱾",
    "alert_selectDetailsAndCode": "ᱫᱚᱭᱟ ᱠᱟᱛᱮ ᱡᱚᱛᱚ ᱵᱤᱵᱚᱨᱚᱱ ᱵᱟᱪᱷᱟᱣ ᱢᱮ ᱟᱨ ᱞᱩᱠᱩ ᱠᱚᱰ ᱵᱷᱚᱨᱟᱣ ᱢᱮ᱾",
    "alert_errorSecretCodeVerification": "ᱞᱩᱠᱩ ᱠᱚᱰ ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣ ᱨᱮ ᱮᱨᱚᱨ ᱦᱩᱭ ᱟᱠᱟᱱᱟ᱾",
    "message_fetchingSocietyDetails": "ᱥᱚᱥᱟᱭᱴᱤ ᱵᱤᱵᱚᱨᱚᱱ ᱞᱟᱹᱜᱤᱫ ᱧᱟᱢᱚᱜ ᱠᱟᱱᱟ...",
    "message_startingCamera": "ᱠᱮᱢᱮᱨᱟ ᱮᱛᱚᱦᱚᱵᱚᱜ ᱠᱟᱱᱟ...",
    "message_verifyingFace": "ᱢᱚᱪᱟ ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣᱚᱜ ᱠᱟᱱᱟ...",
    "message_verifyingCode": "ᱧᱮᱞ ᱵᱟᱪᱷᱟᱣᱚᱜ ᱠᱟᱱᱟ...",
    "ballotPaper": "ᱵᱮᱞᱮᱴ ᱯᱮᱯᱚᱨ"
  }
}
